openapi: 3.0.0

info:
  title: Porta API
  description: The API for the Admin Portal of 3scale
  version: 0.0.0

  servers:
  - url: https://admin.3scale.net
    description: Some random URL for now

paths:
  /applications:
    get:
      summary: Returns a list of applications.
      responses:
        '200':
          description: A JSON array of applications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'
        default:
          description: Unexpected error

components:
  # Reusable schemas (data models)
  schemas:
    Application:
      type: object
      properties:
        name:
          type: string
        state:
          type: string
        account:
          type: string
        plan:
          $ref: '#/components/schemas/Plan'
        created_at:
          type: number
      required:
        - name
        - state
        - account
        - plan
        - created_at
    Plan:
      type: object
      properties:
        name:
          type: string
