---
openapi: 3.0.2
info:
  title: PortaFly
  version: 1.0.0
  description: |
    A tuned API for PortaFly, a Patternfly SPA consuming 3scale Porta API MGMT solution.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /users:
    summary: Users
    description: ""
    get:
      parameters:
      - name: page
        description: Current page for pagination
        schema:
          type: integer
        in: query
      - name: per_page
        description: Number of results per page. Default and max is 500.
        schema:
          type: integer
        in: query
      responses:
        "200":
          $ref: '#/components/responses/userList'
      operationId: getUsers
      summary: Get users
      description: Get a list with all users.
  /applications:
    summary: Applications
    description: ""
    get:
      responses:
        "200":
          $ref: '#/components/responses/applicationsList'
      operationId: getApplications
      summary: Get applications
      description: Get a list with all applications.
  /developer/accounts:
    summary: Accounts
    description: ""
    get:
      parameters:
      - name: page
        description: Page in the paginated list. Defaults to 1.
        schema:
          type: integer
        in: query
      - name: per_page
        description: Number of results per page. Default and max is 500.
        schema:
          type: integer
        in: query
      - name: state
        description: Account state.
        schema:
          type: string
        in: query
      responses:
        "200":
          $ref: '#/components/responses/developerAccountList'
      operationId: getDeveloperAccounts
      summary: Get developer accounts
      description: Get a list with all developer accounts.
components:
  schemas:
    Application:
      title: Application
      description: Represents an application.
      type: object
      properties:
        id:
          description: The application ID number
          type: integer
        name:
          description: The name of the application
          type: string
        state:
          description: The current state of the application
          type: string
        account:
          $ref: '#/components/schemas/DeveloperAccount'
        plan:
          $ref: '#/components/schemas/Plan'
        created_on:
          format: date-time
          description: When it was created
          type: string
        traffic_on:
          format: date-time
          description: ??
          type: string
      example:
        id: 1
        name: Cool App
        state: live
        account:
          $ref: '#/components/examples/accountExample'
        plan:
          $ref: '#/components/examples/planExample'
        created_on: 2020-06-01T00:00:00.000Z
        traffic_on: 2020-06-01T00:00:00.000Z
    Plan:
      title: Plan
      description: Contains all basic information for any plan.
      type: object
      properties:
        id:
          description: The plan ID number
          type: integer
        name:
          description: The name of the plan
          type: string
      example:
        id: 1
        name: Basic Plan
    Account:
      title: Account
      description: Contains all basic information for any account.
      type: object
      properties:
        id:
          description: The account ID number
          type: integer
        org_name:
          description: The organization name
          type: string
      example:
        id: 0
        org_name: Umbrella Corp.
    DeveloperAccount:
      description: Represents an account.
      allOf:
      - $ref: '#/components/schemas/Account'
      - title: Root Type for developerAccountData
        description: A simplified format for a developer account data.
        type: object
        properties:
          created_at:
            format: date-time
            description: When it was created
            type: string
          updated_at:
            format: date-time
            description: When it was last updated
            type: string
          state:
            description: The current state of the account
            type: string
          admin_name:
            description: The name of the admin user
            type: string
          apps_count:
            description: The total amount of applications
            type: integer
        example:
          id: 1
          created_at: 2019-10-18T05:13:26.000Z
          updated_at: 2019-10-18T05:13:27.000Z
          state: approved
          org_name: Umbrella Corp.
          admin_name: Oswell E. Spencer
          apps_count: 3
      example: |-
        id: 1
        org_name: Umbrella Corp.
        admin_name: Oswell E. Spencer
        apps_count: 3
        created_at: 2019-10-18T05:13:26Z
        updated_at: 2019-10-18T05:13:27Z
        state: approved
    User:
      title: Root Type for UserData
      description: Represents a user.
      type: object
      properties:
        id:
          description: The user ID number
          type: integer
        name:
          description: The name of the user
          type: string
        email:
          description: The email of the user
          type: string
        role:
          description: The role of the user
          type: string
        is_current_user:
          description: Is current user logged in?
          type: boolean
        can_see_users:
          description: Can the user see other users?
          type: boolean
        is_authenticated_through_sso:
          description: Is the user authenticated through SSO?
          type: boolean
        can_delete_user:
          description: Can current user delete other users?
          type: boolean
        can_invite_user:
          description: Can the current user invite users?
          type: boolean
        permissions:
          description: List of user permissions
          type: array
          items:
            type: string
  responses:
    applicationsList:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Application'
          example:
          - id: 0,
            name: App 0
            state: suspended
            account:
              $ref: '#/components/examples/accountExample'
            plan:
              $ref: '#/components/examples/planExample'
            created_on: 2020-06-01T00:00:00.000Z
            traffic_on: 2020-06-01T00:00:00.000Z
          - id: 1,
            name: App 1
            state: live
            account:
              $ref: '#/components/examples/accountExample'
            plan:
              $ref: '#/components/examples/planExample'
            created_on: 2020-06-01T01:00:00.000Z
            traffic_on: 2020-06-01T01:00:00.000Z
          - id: 2,
            name: App 2
            state: pending
            account:
              $ref: '#/components/examples/accountExample'
            plan:
              $ref: '#/components/examples/planExample'
            created_on: 2020-06-01T02:00:00.000Z
            traffic_on: 2020-06-01T02:00:00.000Z
      description: Get an account's applications list
    developerAccountList:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/DeveloperAccount'
          example:
          - id: 22
            created_at: 2018-02-10T09:30Z
            updated_at: 2018-02-10T09:30Z
            state: approved
            org_name: Capsule Corp
            admin_name: Dr. Brief
            apps_count: 4
          - id: 72
            created_at: 2018-02-10T09:30Z
            updated_at: 2018-02-10T09:30Z
            state: approved
            org_name: FOXHOUND
            admin_name: Big Boss
            apps_count: 5
          - id: 40
            created_at: 2018-02-11T09:30Z
            updated_at: 2018-02-11T09:30Z
            state: pending
            org_name: B.P.R.D
            admin_name: Dr. Thomas Manning
            apps_count: 10
          - id: 41
            created_at: 2018-02-12T09:30Z
            updated_at: 2018-02-12T09:30Z
            state: approved
            org_name: MomCorp
            admin_name: Mom
            apps_count: 2
          - id: 42
            created_at: 2018-02-12T09:30Z
            updated_at: 2018-02-12T09:30Z
            state: approved
            org_name: Sirius Cybernetics
            admin_name: Admin
            apps_count: 3
          - id: 43
            created_at: 2018-03-10T09:30Z
            updated_at: 2018-03-10T09:30Z
            state: approved
            org_name: Los Pollos Hermanos
            admin_name: Gustavo Fring
            apps_count: 4
      description: Developer accountlist
    userList:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
          examples:
            accountUserListExample:
              value:
              - id: 1
                name: Eric Cartman
                email: eric@southpark.com
                role: admin
                is_current_user: true
                can_see_users: true
                authenticated_through_sso: false
                can_delete_user: true
                can_invite_user: true
              - id: 2
                name: Kyle Broflovski
                email: kyle@southpark.com
                role: member
                permissions:
                - Developer Portal
                - Billing
                - Settings
                is_current_user: false
                can_see_users: true
                authenticated_through_sso: false
                can_delete_user: false
                can_invite_user: false
      description: Account Users List
  examples:
    planExample:
      summary: A sample plan
      value:
        id: 1
        name: Basic Plan
    applicationExample:
      summary: A sample Application
      value:
        id: 1
        name: Racoon City Map
        state: live
        account:
          $ref: '#/components/examples/accountExample'
        plan:
          $ref: '#/components/examples/planExample'
        created_on: 2020-06-01T00:00:00.000Z
        traffic_on: 2020-06-01T00:00:00.000Z
    accountExample:
      summary: A sample account
      value:
        id: 1
        org_name: Umbrella Corp.
