version: 2
# All maintainability checks are enabled by default, but can be disabled or tuned individually under the checks node. Example:
# checks:
#   argument-count:
#     enabled: true
#     config:
#       threshold: 4
plugins:
  shellcheck:
    enabled: true
  brakeman:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-0-92"
    config:
      file: .rubocop.yml
  reek:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
      - .js
      - .jsx
  csslint:
    enabled: false
  coffeelint:
    enabled: true
    checks:
      max_line_length:
        enabled: false
  bundler-audit:
    enabled: true
  scss-lint:
    enabled: true
exclude_patterns:
  - "app/assets/javascripts/plans_widget.js"
  - "app/assets/javascripts/provider/plans_widget.js"
  - "app/javascript/src/patternflyStyles/pf4BaseIE11.scss"
  - "tmp/**/*"
  - "**/vendor/*"
  - "app/assets/patternfly"
  - "app/assets/images/**/*"
  - "public/images/**/*"
  - "public/themes/**/*"
  - "public/javascripts/vendor/*"
  - "public/fancybox/*"
  - "public/assets"
  - "public/packs"
  - 'lib/action_dispatch/rails5_ssl.rb'
  - "lib/developer_portal/app/views/developer_portal/javascripts/*"
  - "lib/developer_portal/app/views/developer_portal/css/*"
  - "lib/developer_portal/app/assets/stylesheets/**/*"
  - "assets/bundles/*.js"
  - "spec/**/*"
  - "spec/**/**/*"
  - "test/**/*"
  - "cdn/*"
  - "app/javascript/src/*/*/*.spec.*"
  - "bin/webpack*"
  - "**/node_modules/"
  - "**/flow-typed"
