version: 2
# All maintainability checks are enabled by default, but can be disabled or tuned individually under the checks node. Example:
# checks:
#   argument-count:
#     enabled: true
#     config:
#       threshold: 4
plugins:
  shellcheck:
    enabled: true
  brakeman:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-1-31"
  reek:
    enabled: true
  csslint:
    enabled: false
  coffeelint:
    enabled: true
    checks:
      max_line_length:
        enabled: false
  bundler-audit:
    enabled: true
  scss-lint:
    enabled: true
exclude_patterns:
  - "**/node_modules/"
  - "**/vendor/*"
  - "app/assets/images/**/*"
  - "app/javascript
  - "assets/bundles/*.js"
  - "bin/webpack*"
  - "cdn/*"
  - "lib/action_dispatch/rails5_ssl.rb"
  - "lib/developer_portal/app/assets/stylesheets/**/*"
  - "lib/developer_portal/app/views/developer_portal/css/*"
  - "lib/developer_portal/app/views/developer_portal/javascripts/*"
  - "public/assets"
  - "public/fancybox/*"
  - "public/images/**/*"
  - "public/javascripts/vendor/*"
  - "public/packs"
  - "public/themes/**/*"
  - "spec/**/*"
  - "spec/**/**/*"
  - "test/**/*"
  - "tmp/**/*"
