version: 2
plugins:
  shellcheck:
    enabled: true
  brakeman:
    enabled: true
  rubocop:
    enabled: true
  reek:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
      - .js
      - .jsx
  csslint:
    enabled: false
  coffeelint:
    enabled: true
    checks:
      max_line_length:
        enabled: false
  bundler-audit:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - db/
    config:
      languages:
        - ruby
        - javascript
exclude_paths:
  - "app/assets/javascripts/plans_widget.js"
  - "app/assets/javascripts/provider/plans_widget.js"
  - "app/javascript/src/patternflyStyles/pf4BaseIE11.scss"
  - "tmp/**/*"
  - "**/vendor/*"
  - "app/assets/patternfly"
  - "app/assets/images/**/*"
  - "public/images/**/*"
  - "public/themes/**/*"
  - "public/javascripts/vendor/*"
  - "public/fancybox/*"
  - 'lib/action_dispatch/rails5_ssl.rb'
  - "lib/developer_portal/app/views/developer_portal/javascripts/*"
  - "lib/developer_portal/app/views/developer_portal/css/*"
  - "lib/developer_portal/app/assets/stylesheets/**/*"
  - "assets/bundles/*.js"
  - "spec/**/*"
  - "spec/**/**/*"
  - "test/**/*"
  - "cdn/*"
  - "app/javascript/src/*/*/*.spec.*"
  - "bin/webpack*"
  - "portafly/config/*"
  - "portafly/scripts/*"
