detectors:
  IrresponsibleModule:
    enabled: false

  TooManyStatements:
    max_statements: 7

  UtilityFunction:
    public_methods_only: true

  UncommunicativeModuleName:
    accept:
      - "/OAuth2/i"

  DuplicateMethodCall:
    allow_calls:
    - "/logger./"

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/observers":
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
