// flow-typed signature: f8b6eb62d24c7a11c6c417719de0fa99
// flow-typed version: <<STUB>>/babel-plugin-react_v^1.0.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react' {
  declare module.exports: any;
}
