// flow-typed signature: 3831e5d983e34442d5fc9f33662786af
// flow-typed version: <<STUB>>/c3_v^0.4.11/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'c3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'c3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'c3/c3' {
  declare module.exports: any;
}

declare module 'c3/c3.min' {
  declare module.exports: any;
}

declare module 'c3/extensions/chart-bubble/bubble' {
  declare module.exports: any;
}

declare module 'c3/extensions/exporter/phantom-exporter' {
  declare module.exports: any;
}

declare module 'c3/extensions/js/c3ext' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/require' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/samples/plugin' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/samples/requirejs' {
  declare module.exports: any;
}

declare module 'c3/htdocs/js/samples/zoom_reduction' {
  declare module.exports: any;
}

declare module 'c3/karma.conf' {
  declare module.exports: any;
}

declare module 'c3/rollup.config' {
  declare module.exports: any;
}

declare module 'c3/spec/api.axis-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.data-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.focus-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.grid-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.load-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.region-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/api.zoom-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/arc-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/axis-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/c3-helper' {
  declare module.exports: any;
}

declare module 'c3/spec/c3-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/class-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/core-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/data-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/data.convert' {
  declare module.exports: any;
}

declare module 'c3/spec/domain-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/grid-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/interaction-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/legend-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/shape.bar-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/shape.line-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/svg-helper' {
  declare module.exports: any;
}

declare module 'c3/spec/title-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/tooltip-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/type-spec' {
  declare module.exports: any;
}

declare module 'c3/spec/zoom-spec' {
  declare module.exports: any;
}

declare module 'c3/src/api.axis' {
  declare module.exports: any;
}

declare module 'c3/src/api.category' {
  declare module.exports: any;
}

declare module 'c3/src/api.chart' {
  declare module.exports: any;
}

declare module 'c3/src/api.color' {
  declare module.exports: any;
}

declare module 'c3/src/api.data' {
  declare module.exports: any;
}

declare module 'c3/src/api.flow' {
  declare module.exports: any;
}

declare module 'c3/src/api.focus' {
  declare module.exports: any;
}

declare module 'c3/src/api.grid' {
  declare module.exports: any;
}

declare module 'c3/src/api.group' {
  declare module.exports: any;
}

declare module 'c3/src/api.legend' {
  declare module.exports: any;
}

declare module 'c3/src/api.load' {
  declare module.exports: any;
}

declare module 'c3/src/api.region' {
  declare module.exports: any;
}

declare module 'c3/src/api.selection' {
  declare module.exports: any;
}

declare module 'c3/src/api.show' {
  declare module.exports: any;
}

declare module 'c3/src/api.tooltip' {
  declare module.exports: any;
}

declare module 'c3/src/api.transform' {
  declare module.exports: any;
}

declare module 'c3/src/api.x' {
  declare module.exports: any;
}

declare module 'c3/src/api.zoom' {
  declare module.exports: any;
}

declare module 'c3/src/arc' {
  declare module.exports: any;
}

declare module 'c3/src/axis' {
  declare module.exports: any;
}

declare module 'c3/src/cache' {
  declare module.exports: any;
}

declare module 'c3/src/category' {
  declare module.exports: any;
}

declare module 'c3/src/class-utils' {
  declare module.exports: any;
}

declare module 'c3/src/class' {
  declare module.exports: any;
}

declare module 'c3/src/clip' {
  declare module.exports: any;
}

declare module 'c3/src/color' {
  declare module.exports: any;
}

declare module 'c3/src/config' {
  declare module.exports: any;
}

declare module 'c3/src/core' {
  declare module.exports: any;
}

declare module 'c3/src/data.convert' {
  declare module.exports: any;
}

declare module 'c3/src/data' {
  declare module.exports: any;
}

declare module 'c3/src/data.load' {
  declare module.exports: any;
}

declare module 'c3/src/domain' {
  declare module.exports: any;
}

declare module 'c3/src/drag' {
  declare module.exports: any;
}

declare module 'c3/src/format' {
  declare module.exports: any;
}

declare module 'c3/src/grid' {
  declare module.exports: any;
}

declare module 'c3/src/index' {
  declare module.exports: any;
}

declare module 'c3/src/interaction' {
  declare module.exports: any;
}

declare module 'c3/src/legend' {
  declare module.exports: any;
}

declare module 'c3/src/polyfill' {
  declare module.exports: any;
}

declare module 'c3/src/region' {
  declare module.exports: any;
}

declare module 'c3/src/scale' {
  declare module.exports: any;
}

declare module 'c3/src/selection' {
  declare module.exports: any;
}

declare module 'c3/src/shape.bar' {
  declare module.exports: any;
}

declare module 'c3/src/shape' {
  declare module.exports: any;
}

declare module 'c3/src/shape.line' {
  declare module.exports: any;
}

declare module 'c3/src/size' {
  declare module.exports: any;
}

declare module 'c3/src/subchart' {
  declare module.exports: any;
}

declare module 'c3/src/text' {
  declare module.exports: any;
}

declare module 'c3/src/title' {
  declare module.exports: any;
}

declare module 'c3/src/tooltip' {
  declare module.exports: any;
}

declare module 'c3/src/type' {
  declare module.exports: any;
}

declare module 'c3/src/ua' {
  declare module.exports: any;
}

declare module 'c3/src/util' {
  declare module.exports: any;
}

declare module 'c3/src/zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'c3/c3.js' {
  declare module.exports: $Exports<'c3/c3'>;
}
declare module 'c3/c3.min.js' {
  declare module.exports: $Exports<'c3/c3.min'>;
}
declare module 'c3/extensions/chart-bubble/bubble.js' {
  declare module.exports: $Exports<'c3/extensions/chart-bubble/bubble'>;
}
declare module 'c3/extensions/exporter/phantom-exporter.js' {
  declare module.exports: $Exports<'c3/extensions/exporter/phantom-exporter'>;
}
declare module 'c3/extensions/js/c3ext.js' {
  declare module.exports: $Exports<'c3/extensions/js/c3ext'>;
}
declare module 'c3/htdocs/js/require.js' {
  declare module.exports: $Exports<'c3/htdocs/js/require'>;
}
declare module 'c3/htdocs/js/samples/plugin.js' {
  declare module.exports: $Exports<'c3/htdocs/js/samples/plugin'>;
}
declare module 'c3/htdocs/js/samples/requirejs.js' {
  declare module.exports: $Exports<'c3/htdocs/js/samples/requirejs'>;
}
declare module 'c3/htdocs/js/samples/zoom_reduction.js' {
  declare module.exports: $Exports<'c3/htdocs/js/samples/zoom_reduction'>;
}
declare module 'c3/karma.conf.js' {
  declare module.exports: $Exports<'c3/karma.conf'>;
}
declare module 'c3/rollup.config.js' {
  declare module.exports: $Exports<'c3/rollup.config'>;
}
declare module 'c3/spec/api.axis-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.axis-spec'>;
}
declare module 'c3/spec/api.data-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.data-spec'>;
}
declare module 'c3/spec/api.focus-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.focus-spec'>;
}
declare module 'c3/spec/api.grid-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.grid-spec'>;
}
declare module 'c3/spec/api.load-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.load-spec'>;
}
declare module 'c3/spec/api.region-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.region-spec'>;
}
declare module 'c3/spec/api.zoom-spec.js' {
  declare module.exports: $Exports<'c3/spec/api.zoom-spec'>;
}
declare module 'c3/spec/arc-spec.js' {
  declare module.exports: $Exports<'c3/spec/arc-spec'>;
}
declare module 'c3/spec/axis-spec.js' {
  declare module.exports: $Exports<'c3/spec/axis-spec'>;
}
declare module 'c3/spec/c3-helper.js' {
  declare module.exports: $Exports<'c3/spec/c3-helper'>;
}
declare module 'c3/spec/c3-spec.js' {
  declare module.exports: $Exports<'c3/spec/c3-spec'>;
}
declare module 'c3/spec/class-spec.js' {
  declare module.exports: $Exports<'c3/spec/class-spec'>;
}
declare module 'c3/spec/core-spec.js' {
  declare module.exports: $Exports<'c3/spec/core-spec'>;
}
declare module 'c3/spec/data-spec.js' {
  declare module.exports: $Exports<'c3/spec/data-spec'>;
}
declare module 'c3/spec/data.convert.js' {
  declare module.exports: $Exports<'c3/spec/data.convert'>;
}
declare module 'c3/spec/domain-spec.js' {
  declare module.exports: $Exports<'c3/spec/domain-spec'>;
}
declare module 'c3/spec/grid-spec.js' {
  declare module.exports: $Exports<'c3/spec/grid-spec'>;
}
declare module 'c3/spec/interaction-spec.js' {
  declare module.exports: $Exports<'c3/spec/interaction-spec'>;
}
declare module 'c3/spec/legend-spec.js' {
  declare module.exports: $Exports<'c3/spec/legend-spec'>;
}
declare module 'c3/spec/shape.bar-spec.js' {
  declare module.exports: $Exports<'c3/spec/shape.bar-spec'>;
}
declare module 'c3/spec/shape.line-spec.js' {
  declare module.exports: $Exports<'c3/spec/shape.line-spec'>;
}
declare module 'c3/spec/svg-helper.js' {
  declare module.exports: $Exports<'c3/spec/svg-helper'>;
}
declare module 'c3/spec/title-spec.js' {
  declare module.exports: $Exports<'c3/spec/title-spec'>;
}
declare module 'c3/spec/tooltip-spec.js' {
  declare module.exports: $Exports<'c3/spec/tooltip-spec'>;
}
declare module 'c3/spec/type-spec.js' {
  declare module.exports: $Exports<'c3/spec/type-spec'>;
}
declare module 'c3/spec/zoom-spec.js' {
  declare module.exports: $Exports<'c3/spec/zoom-spec'>;
}
declare module 'c3/src/api.axis.js' {
  declare module.exports: $Exports<'c3/src/api.axis'>;
}
declare module 'c3/src/api.category.js' {
  declare module.exports: $Exports<'c3/src/api.category'>;
}
declare module 'c3/src/api.chart.js' {
  declare module.exports: $Exports<'c3/src/api.chart'>;
}
declare module 'c3/src/api.color.js' {
  declare module.exports: $Exports<'c3/src/api.color'>;
}
declare module 'c3/src/api.data.js' {
  declare module.exports: $Exports<'c3/src/api.data'>;
}
declare module 'c3/src/api.flow.js' {
  declare module.exports: $Exports<'c3/src/api.flow'>;
}
declare module 'c3/src/api.focus.js' {
  declare module.exports: $Exports<'c3/src/api.focus'>;
}
declare module 'c3/src/api.grid.js' {
  declare module.exports: $Exports<'c3/src/api.grid'>;
}
declare module 'c3/src/api.group.js' {
  declare module.exports: $Exports<'c3/src/api.group'>;
}
declare module 'c3/src/api.legend.js' {
  declare module.exports: $Exports<'c3/src/api.legend'>;
}
declare module 'c3/src/api.load.js' {
  declare module.exports: $Exports<'c3/src/api.load'>;
}
declare module 'c3/src/api.region.js' {
  declare module.exports: $Exports<'c3/src/api.region'>;
}
declare module 'c3/src/api.selection.js' {
  declare module.exports: $Exports<'c3/src/api.selection'>;
}
declare module 'c3/src/api.show.js' {
  declare module.exports: $Exports<'c3/src/api.show'>;
}
declare module 'c3/src/api.tooltip.js' {
  declare module.exports: $Exports<'c3/src/api.tooltip'>;
}
declare module 'c3/src/api.transform.js' {
  declare module.exports: $Exports<'c3/src/api.transform'>;
}
declare module 'c3/src/api.x.js' {
  declare module.exports: $Exports<'c3/src/api.x'>;
}
declare module 'c3/src/api.zoom.js' {
  declare module.exports: $Exports<'c3/src/api.zoom'>;
}
declare module 'c3/src/arc.js' {
  declare module.exports: $Exports<'c3/src/arc'>;
}
declare module 'c3/src/axis.js' {
  declare module.exports: $Exports<'c3/src/axis'>;
}
declare module 'c3/src/cache.js' {
  declare module.exports: $Exports<'c3/src/cache'>;
}
declare module 'c3/src/category.js' {
  declare module.exports: $Exports<'c3/src/category'>;
}
declare module 'c3/src/class-utils.js' {
  declare module.exports: $Exports<'c3/src/class-utils'>;
}
declare module 'c3/src/class.js' {
  declare module.exports: $Exports<'c3/src/class'>;
}
declare module 'c3/src/clip.js' {
  declare module.exports: $Exports<'c3/src/clip'>;
}
declare module 'c3/src/color.js' {
  declare module.exports: $Exports<'c3/src/color'>;
}
declare module 'c3/src/config.js' {
  declare module.exports: $Exports<'c3/src/config'>;
}
declare module 'c3/src/core.js' {
  declare module.exports: $Exports<'c3/src/core'>;
}
declare module 'c3/src/data.convert.js' {
  declare module.exports: $Exports<'c3/src/data.convert'>;
}
declare module 'c3/src/data.js' {
  declare module.exports: $Exports<'c3/src/data'>;
}
declare module 'c3/src/data.load.js' {
  declare module.exports: $Exports<'c3/src/data.load'>;
}
declare module 'c3/src/domain.js' {
  declare module.exports: $Exports<'c3/src/domain'>;
}
declare module 'c3/src/drag.js' {
  declare module.exports: $Exports<'c3/src/drag'>;
}
declare module 'c3/src/format.js' {
  declare module.exports: $Exports<'c3/src/format'>;
}
declare module 'c3/src/grid.js' {
  declare module.exports: $Exports<'c3/src/grid'>;
}
declare module 'c3/src/index.js' {
  declare module.exports: $Exports<'c3/src/index'>;
}
declare module 'c3/src/interaction.js' {
  declare module.exports: $Exports<'c3/src/interaction'>;
}
declare module 'c3/src/legend.js' {
  declare module.exports: $Exports<'c3/src/legend'>;
}
declare module 'c3/src/polyfill.js' {
  declare module.exports: $Exports<'c3/src/polyfill'>;
}
declare module 'c3/src/region.js' {
  declare module.exports: $Exports<'c3/src/region'>;
}
declare module 'c3/src/scale.js' {
  declare module.exports: $Exports<'c3/src/scale'>;
}
declare module 'c3/src/selection.js' {
  declare module.exports: $Exports<'c3/src/selection'>;
}
declare module 'c3/src/shape.bar.js' {
  declare module.exports: $Exports<'c3/src/shape.bar'>;
}
declare module 'c3/src/shape.js' {
  declare module.exports: $Exports<'c3/src/shape'>;
}
declare module 'c3/src/shape.line.js' {
  declare module.exports: $Exports<'c3/src/shape.line'>;
}
declare module 'c3/src/size.js' {
  declare module.exports: $Exports<'c3/src/size'>;
}
declare module 'c3/src/subchart.js' {
  declare module.exports: $Exports<'c3/src/subchart'>;
}
declare module 'c3/src/text.js' {
  declare module.exports: $Exports<'c3/src/text'>;
}
declare module 'c3/src/title.js' {
  declare module.exports: $Exports<'c3/src/title'>;
}
declare module 'c3/src/tooltip.js' {
  declare module.exports: $Exports<'c3/src/tooltip'>;
}
declare module 'c3/src/type.js' {
  declare module.exports: $Exports<'c3/src/type'>;
}
declare module 'c3/src/ua.js' {
  declare module.exports: $Exports<'c3/src/ua'>;
}
declare module 'c3/src/util.js' {
  declare module.exports: $Exports<'c3/src/util'>;
}
declare module 'c3/src/zoom.js' {
  declare module.exports: $Exports<'c3/src/zoom'>;
}
