// flow-typed signature: d7ab114ac02ced999bc0f9b2b484a771
// flow-typed version: <<STUB>>/decca_v^2.3.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'decca'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'decca' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'decca/lib/build' {
  declare module.exports: any;
}

declare module 'decca/lib/dom' {
  declare module.exports: any;
}

declare module 'decca/lib/element' {
  declare module.exports: any;
}

declare module 'decca/lib/fix_props' {
  declare module.exports: any;
}

declare module 'decca/lib/id' {
  declare module.exports: any;
}

declare module 'decca/lib/index' {
  declare module.exports: any;
}

declare module 'decca/lib/string' {
  declare module.exports: any;
}

declare module 'decca/lib/widget' {
  declare module.exports: any;
}

// Filename aliases
declare module 'decca/lib/build.js' {
  declare module.exports: $Exports<'decca/lib/build'>;
}
declare module 'decca/lib/dom.js' {
  declare module.exports: $Exports<'decca/lib/dom'>;
}
declare module 'decca/lib/element.js' {
  declare module.exports: $Exports<'decca/lib/element'>;
}
declare module 'decca/lib/fix_props.js' {
  declare module.exports: $Exports<'decca/lib/fix_props'>;
}
declare module 'decca/lib/id.js' {
  declare module.exports: $Exports<'decca/lib/id'>;
}
declare module 'decca/lib/index.js' {
  declare module.exports: $Exports<'decca/lib/index'>;
}
declare module 'decca/lib/string.js' {
  declare module.exports: $Exports<'decca/lib/string'>;
}
declare module 'decca/lib/widget.js' {
  declare module.exports: $Exports<'decca/lib/widget'>;
}
