// flow-typed signature: bddacd1371f96d60d94f1ddbf47cf9f9
// flow-typed version: <<STUB>>/hosted-git-info_vhttps://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.1.5.tgz/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hosted-git-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hosted-git-info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hosted-git-info/git-host-info' {
  declare module.exports: any;
}

declare module 'hosted-git-info/git-host' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hosted-git-info/git-host-info.js' {
  declare module.exports: $Exports<'hosted-git-info/git-host-info'>;
}
declare module 'hosted-git-info/git-host.js' {
  declare module.exports: $Exports<'hosted-git-info/git-host'>;
}
declare module 'hosted-git-info/index' {
  declare module.exports: $Exports<'hosted-git-info'>;
}
declare module 'hosted-git-info/index.js' {
  declare module.exports: $Exports<'hosted-git-info'>;
}
