// flow-typed signature: 82a3fb8918f8109df88d0ad68d0e5979
// flow-typed version: <<STUB>>/jasmine_v^3.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine/bin/jasmine' {
  declare module.exports: any;
}

declare module 'jasmine/Gruntfile' {
  declare module.exports: any;
}

declare module 'jasmine/lib/command' {
  declare module.exports: any;
}

declare module 'jasmine/lib/filters/console_spec_filter' {
  declare module.exports: any;
}

declare module 'jasmine/lib/jasmine' {
  declare module.exports: any;
}

declare module 'jasmine/lib/reporters/completion_reporter' {
  declare module.exports: any;
}

declare module 'jasmine/lib/reporters/console_reporter' {
  declare module.exports: any;
}

declare module 'jasmine/tasks/jasmine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine/bin/jasmine.js' {
  declare module.exports: $Exports<'jasmine/bin/jasmine'>;
}
declare module 'jasmine/Gruntfile.js' {
  declare module.exports: $Exports<'jasmine/Gruntfile'>;
}
declare module 'jasmine/lib/command.js' {
  declare module.exports: $Exports<'jasmine/lib/command'>;
}
declare module 'jasmine/lib/filters/console_spec_filter.js' {
  declare module.exports: $Exports<'jasmine/lib/filters/console_spec_filter'>;
}
declare module 'jasmine/lib/jasmine.js' {
  declare module.exports: $Exports<'jasmine/lib/jasmine'>;
}
declare module 'jasmine/lib/reporters/completion_reporter.js' {
  declare module.exports: $Exports<'jasmine/lib/reporters/completion_reporter'>;
}
declare module 'jasmine/lib/reporters/console_reporter.js' {
  declare module.exports: $Exports<'jasmine/lib/reporters/console_reporter'>;
}
declare module 'jasmine/tasks/jasmine.js' {
  declare module.exports: $Exports<'jasmine/tasks/jasmine'>;
}
