// flow-typed signature: fca2e9ec5658ace15f8c487bfb3ad1cd
// flow-typed version: <<STUB>>/jasmine-jquery_v^2.1.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-jquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-jquery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-jquery/lib/jasmine-jquery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-jquery/lib/jasmine-jquery.js' {
  declare module.exports: $Exports<'jasmine-jquery/lib/jasmine-jquery'>;
}
