// flow-typed signature: b10cf91a55f7fb0fded1180b116aea31
// flow-typed version: <<STUB>>/jquery-ui_v^1.12.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jquery-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jquery-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jquery-ui/build/release-test' {
  declare module.exports: any;
}

declare module 'jquery-ui/build/release' {
  declare module.exports: any;
}

declare module 'jquery-ui/build/tasks/build' {
  declare module.exports: any;
}

declare module 'jquery-ui/build/tasks/testswarm' {
  declare module.exports: any;
}

declare module 'jquery-ui/demos/bootstrap' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/globalize/globalize.culture.de-DE' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/globalize/globalize.culture.ja-JP' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/globalize/globalize' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.10.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.10.1/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.10.2/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.11.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.11.1/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.11.2/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.11.3/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.12.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.12.1/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.12.2/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.12.3/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.12.4/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.7.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.7.1/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.7.2/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.8.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.8.1/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.8.2/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.8.3/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.9.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-1.9.1/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.0.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.0.1/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.0.2/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.0.3/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.1.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.1.1/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.1.2/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.1.3/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.1.4/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.2.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.2.1/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.2.2/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.2.3/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-2.2.4/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-3.0.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-3.1.0/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-custom/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-mousewheel/jquery.mousewheel' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery-simulate/jquery.simulate' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jquery/jquery' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/jshint/jshint' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/qunit-assert-classes/qunit-assert-classes' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/qunit-assert-close/qunit-assert-close' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/qunit-composite/qunit-composite' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/qunit/qunit' {
  declare module.exports: any;
}

declare module 'jquery-ui/external/requirejs/require' {
  declare module.exports: any;
}

declare module 'jquery-ui/Gruntfile' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/index' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/lib/bootstrap' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/lib/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/lib/css' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/lib/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/lib/qunit-assert-domequal' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/lib/qunit' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/accordion/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/accordion/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/accordion/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/accordion/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/accordion/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/accordion/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/autocomplete/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/autocomplete/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/autocomplete/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/autocomplete/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/autocomplete/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/button/common-deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/button/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/button/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/button/deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/button/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/button/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/button/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/checkboxradio/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/checkboxradio/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/checkboxradio/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/checkboxradio/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/checkboxradio/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/controlgroup/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/controlgroup/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/controlgroup/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/controlgroup/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/core/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/core/selector' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/datepicker/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/datepicker/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/datepicker/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/datepicker/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/datepicker/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/datepicker/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/dialog/common-deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/dialog/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/dialog/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/dialog/deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/dialog/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/dialog/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/dialog/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/dialog/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/draggable/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/draggable/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/draggable/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/draggable/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/draggable/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/draggable/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/droppable/common-deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/droppable/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/droppable/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/droppable/deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/droppable/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/droppable/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/droppable/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/droppable/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/effects/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/effects/scale' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/form-reset-mixin/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/menu/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/menu/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/menu/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/menu/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/menu/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/menu/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/position/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/progressbar/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/progressbar/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/progressbar/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/progressbar/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/progressbar/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/resizable/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/resizable/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/resizable/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/resizable/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/resizable/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/resizable/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectable/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectable/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectable/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectable/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectable/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectmenu/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectmenu/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectmenu/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectmenu/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/selectmenu/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/slider/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/slider/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/slider/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/slider/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/slider/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/sortable/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/sortable/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/sortable/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/sortable/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/sortable/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/sortable/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/spinner/common-deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/spinner/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/spinner/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/spinner/deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/spinner/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/spinner/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/spinner/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/spinner/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/subsuite' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tabs/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tabs/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tabs/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tabs/helper' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tabs/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tabs/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tooltip/common-deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tooltip/common' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tooltip/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tooltip/deprecated' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tooltip/events' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tooltip/methods' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/tooltip/options' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/widget/animation' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/widget/classes' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/widget/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/unit/widget/extend' {
  declare module.exports: any;
}

declare module 'jquery-ui/tests/visual/effects/effects' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/core' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/data' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/disable-selection' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effect' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-blind' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-bounce' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-clip' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-drop' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-explode' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-fade' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-fold' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-highlight' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-puff' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-pulsate' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-scale' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-shake' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-size' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-slide' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/effects/effect-transfer' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/escape-selector' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/focusable' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/form-reset-mixin' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/form' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-af' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ar-DZ' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ar' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-az' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-be' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-bg' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-bs' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ca' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-cs' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-cy-GB' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-da' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-de' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-el' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-en-AU' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-en-GB' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-en-NZ' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-eo' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-es' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-et' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-eu' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-fa' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-fi' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-fo' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-fr-CA' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-fr-CH' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-fr' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-gl' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-he' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-hi' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-hr' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-hu' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-hy' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-id' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-is' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-it-CH' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-it' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ja' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ka' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-kk' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-km' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ko' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ky' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-lb' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-lt' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-lv' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-mk' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ml' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ms' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-nb' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-nl-BE' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-nl' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-nn' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-no' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-pl' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-pt-BR' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-pt' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-rm' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ro' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ru' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-sk' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-sl' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-sq' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-sr-SR' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-sr' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-sv' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-ta' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-th' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-tj' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-tr' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-uk' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-vi' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-zh-CN' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-zh-HK' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/i18n/datepicker-zh-TW' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/ie' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/jquery-1-7' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/keycode' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/labels' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/plugin' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/position' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/safe-active-element' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/safe-blur' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/scroll-parent' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/tabbable' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/unique-id' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/version' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widget' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/accordion' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/autocomplete' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/button' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/checkboxradio' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/controlgroup' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/datepicker' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/dialog' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/draggable' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/droppable' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/menu' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/mouse' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/progressbar' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/resizable' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/selectable' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/selectmenu' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/slider' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/sortable' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/spinner' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/tabs' {
  declare module.exports: any;
}

declare module 'jquery-ui/ui/widgets/tooltip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jquery-ui/build/release-test.js' {
  declare module.exports: $Exports<'jquery-ui/build/release-test'>;
}
declare module 'jquery-ui/build/release.js' {
  declare module.exports: $Exports<'jquery-ui/build/release'>;
}
declare module 'jquery-ui/build/tasks/build.js' {
  declare module.exports: $Exports<'jquery-ui/build/tasks/build'>;
}
declare module 'jquery-ui/build/tasks/testswarm.js' {
  declare module.exports: $Exports<'jquery-ui/build/tasks/testswarm'>;
}
declare module 'jquery-ui/demos/bootstrap.js' {
  declare module.exports: $Exports<'jquery-ui/demos/bootstrap'>;
}
declare module 'jquery-ui/external/globalize/globalize.culture.de-DE.js' {
  declare module.exports: $Exports<'jquery-ui/external/globalize/globalize.culture.de-DE'>;
}
declare module 'jquery-ui/external/globalize/globalize.culture.ja-JP.js' {
  declare module.exports: $Exports<'jquery-ui/external/globalize/globalize.culture.ja-JP'>;
}
declare module 'jquery-ui/external/globalize/globalize.js' {
  declare module.exports: $Exports<'jquery-ui/external/globalize/globalize'>;
}
declare module 'jquery-ui/external/jquery-1.10.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.10.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.10.1/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.10.1/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.10.2/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.10.2/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.11.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.11.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.11.1/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.11.1/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.11.2/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.11.2/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.11.3/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.11.3/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.12.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.12.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.12.1/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.12.1/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.12.2/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.12.2/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.12.3/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.12.3/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.12.4/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.12.4/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.7.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.7.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.7.1/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.7.1/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.7.2/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.7.2/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.8.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.8.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.8.1/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.8.1/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.8.2/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.8.2/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.8.3/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.8.3/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.9.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.9.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-1.9.1/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-1.9.1/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.0.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.0.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.0.1/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.0.1/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.0.2/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.0.2/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.0.3/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.0.3/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.1.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.1.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.1.1/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.1.1/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.1.2/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.1.2/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.1.3/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.1.3/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.1.4/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.1.4/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.2.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.2.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.2.1/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.2.1/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.2.2/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.2.2/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.2.3/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.2.3/jquery'>;
}
declare module 'jquery-ui/external/jquery-2.2.4/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-2.2.4/jquery'>;
}
declare module 'jquery-ui/external/jquery-3.0.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-3.0.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-3.1.0/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-3.1.0/jquery'>;
}
declare module 'jquery-ui/external/jquery-custom/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-custom/jquery'>;
}
declare module 'jquery-ui/external/jquery-mousewheel/jquery.mousewheel.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-mousewheel/jquery.mousewheel'>;
}
declare module 'jquery-ui/external/jquery-simulate/jquery.simulate.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery-simulate/jquery.simulate'>;
}
declare module 'jquery-ui/external/jquery/jquery.js' {
  declare module.exports: $Exports<'jquery-ui/external/jquery/jquery'>;
}
declare module 'jquery-ui/external/jshint/jshint.js' {
  declare module.exports: $Exports<'jquery-ui/external/jshint/jshint'>;
}
declare module 'jquery-ui/external/qunit-assert-classes/qunit-assert-classes.js' {
  declare module.exports: $Exports<'jquery-ui/external/qunit-assert-classes/qunit-assert-classes'>;
}
declare module 'jquery-ui/external/qunit-assert-close/qunit-assert-close.js' {
  declare module.exports: $Exports<'jquery-ui/external/qunit-assert-close/qunit-assert-close'>;
}
declare module 'jquery-ui/external/qunit-composite/qunit-composite.js' {
  declare module.exports: $Exports<'jquery-ui/external/qunit-composite/qunit-composite'>;
}
declare module 'jquery-ui/external/qunit/qunit.js' {
  declare module.exports: $Exports<'jquery-ui/external/qunit/qunit'>;
}
declare module 'jquery-ui/external/requirejs/require.js' {
  declare module.exports: $Exports<'jquery-ui/external/requirejs/require'>;
}
declare module 'jquery-ui/Gruntfile.js' {
  declare module.exports: $Exports<'jquery-ui/Gruntfile'>;
}
declare module 'jquery-ui/tests/index.js' {
  declare module.exports: $Exports<'jquery-ui/tests/index'>;
}
declare module 'jquery-ui/tests/lib/bootstrap.js' {
  declare module.exports: $Exports<'jquery-ui/tests/lib/bootstrap'>;
}
declare module 'jquery-ui/tests/lib/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/lib/common'>;
}
declare module 'jquery-ui/tests/lib/css.js' {
  declare module.exports: $Exports<'jquery-ui/tests/lib/css'>;
}
declare module 'jquery-ui/tests/lib/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/lib/helper'>;
}
declare module 'jquery-ui/tests/lib/qunit-assert-domequal.js' {
  declare module.exports: $Exports<'jquery-ui/tests/lib/qunit-assert-domequal'>;
}
declare module 'jquery-ui/tests/lib/qunit.js' {
  declare module.exports: $Exports<'jquery-ui/tests/lib/qunit'>;
}
declare module 'jquery-ui/tests/unit/accordion/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/accordion/common'>;
}
declare module 'jquery-ui/tests/unit/accordion/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/accordion/core'>;
}
declare module 'jquery-ui/tests/unit/accordion/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/accordion/events'>;
}
declare module 'jquery-ui/tests/unit/accordion/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/accordion/helper'>;
}
declare module 'jquery-ui/tests/unit/accordion/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/accordion/methods'>;
}
declare module 'jquery-ui/tests/unit/accordion/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/accordion/options'>;
}
declare module 'jquery-ui/tests/unit/autocomplete/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/autocomplete/common'>;
}
declare module 'jquery-ui/tests/unit/autocomplete/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/autocomplete/core'>;
}
declare module 'jquery-ui/tests/unit/autocomplete/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/autocomplete/events'>;
}
declare module 'jquery-ui/tests/unit/autocomplete/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/autocomplete/methods'>;
}
declare module 'jquery-ui/tests/unit/autocomplete/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/autocomplete/options'>;
}
declare module 'jquery-ui/tests/unit/button/common-deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/button/common-deprecated'>;
}
declare module 'jquery-ui/tests/unit/button/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/button/common'>;
}
declare module 'jquery-ui/tests/unit/button/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/button/core'>;
}
declare module 'jquery-ui/tests/unit/button/deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/button/deprecated'>;
}
declare module 'jquery-ui/tests/unit/button/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/button/events'>;
}
declare module 'jquery-ui/tests/unit/button/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/button/methods'>;
}
declare module 'jquery-ui/tests/unit/button/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/button/options'>;
}
declare module 'jquery-ui/tests/unit/checkboxradio/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/checkboxradio/common'>;
}
declare module 'jquery-ui/tests/unit/checkboxradio/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/checkboxradio/core'>;
}
declare module 'jquery-ui/tests/unit/checkboxradio/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/checkboxradio/events'>;
}
declare module 'jquery-ui/tests/unit/checkboxradio/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/checkboxradio/methods'>;
}
declare module 'jquery-ui/tests/unit/checkboxradio/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/checkboxradio/options'>;
}
declare module 'jquery-ui/tests/unit/controlgroup/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/controlgroup/common'>;
}
declare module 'jquery-ui/tests/unit/controlgroup/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/controlgroup/core'>;
}
declare module 'jquery-ui/tests/unit/controlgroup/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/controlgroup/methods'>;
}
declare module 'jquery-ui/tests/unit/controlgroup/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/controlgroup/options'>;
}
declare module 'jquery-ui/tests/unit/core/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/core/core'>;
}
declare module 'jquery-ui/tests/unit/core/selector.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/core/selector'>;
}
declare module 'jquery-ui/tests/unit/datepicker/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/datepicker/common'>;
}
declare module 'jquery-ui/tests/unit/datepicker/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/datepicker/core'>;
}
declare module 'jquery-ui/tests/unit/datepicker/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/datepicker/events'>;
}
declare module 'jquery-ui/tests/unit/datepicker/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/datepicker/helper'>;
}
declare module 'jquery-ui/tests/unit/datepicker/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/datepicker/methods'>;
}
declare module 'jquery-ui/tests/unit/datepicker/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/datepicker/options'>;
}
declare module 'jquery-ui/tests/unit/dialog/common-deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/dialog/common-deprecated'>;
}
declare module 'jquery-ui/tests/unit/dialog/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/dialog/common'>;
}
declare module 'jquery-ui/tests/unit/dialog/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/dialog/core'>;
}
declare module 'jquery-ui/tests/unit/dialog/deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/dialog/deprecated'>;
}
declare module 'jquery-ui/tests/unit/dialog/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/dialog/events'>;
}
declare module 'jquery-ui/tests/unit/dialog/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/dialog/helper'>;
}
declare module 'jquery-ui/tests/unit/dialog/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/dialog/methods'>;
}
declare module 'jquery-ui/tests/unit/dialog/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/dialog/options'>;
}
declare module 'jquery-ui/tests/unit/draggable/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/draggable/common'>;
}
declare module 'jquery-ui/tests/unit/draggable/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/draggable/core'>;
}
declare module 'jquery-ui/tests/unit/draggable/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/draggable/events'>;
}
declare module 'jquery-ui/tests/unit/draggable/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/draggable/helper'>;
}
declare module 'jquery-ui/tests/unit/draggable/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/draggable/methods'>;
}
declare module 'jquery-ui/tests/unit/draggable/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/draggable/options'>;
}
declare module 'jquery-ui/tests/unit/droppable/common-deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/droppable/common-deprecated'>;
}
declare module 'jquery-ui/tests/unit/droppable/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/droppable/common'>;
}
declare module 'jquery-ui/tests/unit/droppable/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/droppable/core'>;
}
declare module 'jquery-ui/tests/unit/droppable/deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/droppable/deprecated'>;
}
declare module 'jquery-ui/tests/unit/droppable/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/droppable/events'>;
}
declare module 'jquery-ui/tests/unit/droppable/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/droppable/helper'>;
}
declare module 'jquery-ui/tests/unit/droppable/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/droppable/methods'>;
}
declare module 'jquery-ui/tests/unit/droppable/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/droppable/options'>;
}
declare module 'jquery-ui/tests/unit/effects/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/effects/core'>;
}
declare module 'jquery-ui/tests/unit/effects/scale.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/effects/scale'>;
}
declare module 'jquery-ui/tests/unit/form-reset-mixin/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/form-reset-mixin/core'>;
}
declare module 'jquery-ui/tests/unit/menu/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/menu/common'>;
}
declare module 'jquery-ui/tests/unit/menu/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/menu/core'>;
}
declare module 'jquery-ui/tests/unit/menu/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/menu/events'>;
}
declare module 'jquery-ui/tests/unit/menu/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/menu/helper'>;
}
declare module 'jquery-ui/tests/unit/menu/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/menu/methods'>;
}
declare module 'jquery-ui/tests/unit/menu/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/menu/options'>;
}
declare module 'jquery-ui/tests/unit/position/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/position/core'>;
}
declare module 'jquery-ui/tests/unit/progressbar/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/progressbar/common'>;
}
declare module 'jquery-ui/tests/unit/progressbar/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/progressbar/core'>;
}
declare module 'jquery-ui/tests/unit/progressbar/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/progressbar/events'>;
}
declare module 'jquery-ui/tests/unit/progressbar/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/progressbar/methods'>;
}
declare module 'jquery-ui/tests/unit/progressbar/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/progressbar/options'>;
}
declare module 'jquery-ui/tests/unit/resizable/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/resizable/common'>;
}
declare module 'jquery-ui/tests/unit/resizable/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/resizable/core'>;
}
declare module 'jquery-ui/tests/unit/resizable/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/resizable/events'>;
}
declare module 'jquery-ui/tests/unit/resizable/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/resizable/helper'>;
}
declare module 'jquery-ui/tests/unit/resizable/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/resizable/methods'>;
}
declare module 'jquery-ui/tests/unit/resizable/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/resizable/options'>;
}
declare module 'jquery-ui/tests/unit/selectable/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectable/common'>;
}
declare module 'jquery-ui/tests/unit/selectable/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectable/core'>;
}
declare module 'jquery-ui/tests/unit/selectable/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectable/events'>;
}
declare module 'jquery-ui/tests/unit/selectable/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectable/methods'>;
}
declare module 'jquery-ui/tests/unit/selectable/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectable/options'>;
}
declare module 'jquery-ui/tests/unit/selectmenu/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectmenu/common'>;
}
declare module 'jquery-ui/tests/unit/selectmenu/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectmenu/core'>;
}
declare module 'jquery-ui/tests/unit/selectmenu/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectmenu/events'>;
}
declare module 'jquery-ui/tests/unit/selectmenu/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectmenu/methods'>;
}
declare module 'jquery-ui/tests/unit/selectmenu/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/selectmenu/options'>;
}
declare module 'jquery-ui/tests/unit/slider/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/slider/common'>;
}
declare module 'jquery-ui/tests/unit/slider/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/slider/core'>;
}
declare module 'jquery-ui/tests/unit/slider/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/slider/events'>;
}
declare module 'jquery-ui/tests/unit/slider/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/slider/methods'>;
}
declare module 'jquery-ui/tests/unit/slider/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/slider/options'>;
}
declare module 'jquery-ui/tests/unit/sortable/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/sortable/common'>;
}
declare module 'jquery-ui/tests/unit/sortable/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/sortable/core'>;
}
declare module 'jquery-ui/tests/unit/sortable/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/sortable/events'>;
}
declare module 'jquery-ui/tests/unit/sortable/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/sortable/helper'>;
}
declare module 'jquery-ui/tests/unit/sortable/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/sortable/methods'>;
}
declare module 'jquery-ui/tests/unit/sortable/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/sortable/options'>;
}
declare module 'jquery-ui/tests/unit/spinner/common-deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/spinner/common-deprecated'>;
}
declare module 'jquery-ui/tests/unit/spinner/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/spinner/common'>;
}
declare module 'jquery-ui/tests/unit/spinner/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/spinner/core'>;
}
declare module 'jquery-ui/tests/unit/spinner/deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/spinner/deprecated'>;
}
declare module 'jquery-ui/tests/unit/spinner/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/spinner/events'>;
}
declare module 'jquery-ui/tests/unit/spinner/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/spinner/helper'>;
}
declare module 'jquery-ui/tests/unit/spinner/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/spinner/methods'>;
}
declare module 'jquery-ui/tests/unit/spinner/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/spinner/options'>;
}
declare module 'jquery-ui/tests/unit/subsuite.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/subsuite'>;
}
declare module 'jquery-ui/tests/unit/tabs/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tabs/common'>;
}
declare module 'jquery-ui/tests/unit/tabs/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tabs/core'>;
}
declare module 'jquery-ui/tests/unit/tabs/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tabs/events'>;
}
declare module 'jquery-ui/tests/unit/tabs/helper.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tabs/helper'>;
}
declare module 'jquery-ui/tests/unit/tabs/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tabs/methods'>;
}
declare module 'jquery-ui/tests/unit/tabs/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tabs/options'>;
}
declare module 'jquery-ui/tests/unit/tooltip/common-deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tooltip/common-deprecated'>;
}
declare module 'jquery-ui/tests/unit/tooltip/common.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tooltip/common'>;
}
declare module 'jquery-ui/tests/unit/tooltip/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tooltip/core'>;
}
declare module 'jquery-ui/tests/unit/tooltip/deprecated.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tooltip/deprecated'>;
}
declare module 'jquery-ui/tests/unit/tooltip/events.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tooltip/events'>;
}
declare module 'jquery-ui/tests/unit/tooltip/methods.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tooltip/methods'>;
}
declare module 'jquery-ui/tests/unit/tooltip/options.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/tooltip/options'>;
}
declare module 'jquery-ui/tests/unit/widget/animation.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/widget/animation'>;
}
declare module 'jquery-ui/tests/unit/widget/classes.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/widget/classes'>;
}
declare module 'jquery-ui/tests/unit/widget/core.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/widget/core'>;
}
declare module 'jquery-ui/tests/unit/widget/extend.js' {
  declare module.exports: $Exports<'jquery-ui/tests/unit/widget/extend'>;
}
declare module 'jquery-ui/tests/visual/effects/effects.js' {
  declare module.exports: $Exports<'jquery-ui/tests/visual/effects/effects'>;
}
declare module 'jquery-ui/ui/core.js' {
  declare module.exports: $Exports<'jquery-ui/ui/core'>;
}
declare module 'jquery-ui/ui/data.js' {
  declare module.exports: $Exports<'jquery-ui/ui/data'>;
}
declare module 'jquery-ui/ui/disable-selection.js' {
  declare module.exports: $Exports<'jquery-ui/ui/disable-selection'>;
}
declare module 'jquery-ui/ui/effect.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effect'>;
}
declare module 'jquery-ui/ui/effects/effect-blind.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-blind'>;
}
declare module 'jquery-ui/ui/effects/effect-bounce.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-bounce'>;
}
declare module 'jquery-ui/ui/effects/effect-clip.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-clip'>;
}
declare module 'jquery-ui/ui/effects/effect-drop.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-drop'>;
}
declare module 'jquery-ui/ui/effects/effect-explode.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-explode'>;
}
declare module 'jquery-ui/ui/effects/effect-fade.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-fade'>;
}
declare module 'jquery-ui/ui/effects/effect-fold.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-fold'>;
}
declare module 'jquery-ui/ui/effects/effect-highlight.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-highlight'>;
}
declare module 'jquery-ui/ui/effects/effect-puff.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-puff'>;
}
declare module 'jquery-ui/ui/effects/effect-pulsate.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-pulsate'>;
}
declare module 'jquery-ui/ui/effects/effect-scale.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-scale'>;
}
declare module 'jquery-ui/ui/effects/effect-shake.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-shake'>;
}
declare module 'jquery-ui/ui/effects/effect-size.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-size'>;
}
declare module 'jquery-ui/ui/effects/effect-slide.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-slide'>;
}
declare module 'jquery-ui/ui/effects/effect-transfer.js' {
  declare module.exports: $Exports<'jquery-ui/ui/effects/effect-transfer'>;
}
declare module 'jquery-ui/ui/escape-selector.js' {
  declare module.exports: $Exports<'jquery-ui/ui/escape-selector'>;
}
declare module 'jquery-ui/ui/focusable.js' {
  declare module.exports: $Exports<'jquery-ui/ui/focusable'>;
}
declare module 'jquery-ui/ui/form-reset-mixin.js' {
  declare module.exports: $Exports<'jquery-ui/ui/form-reset-mixin'>;
}
declare module 'jquery-ui/ui/form.js' {
  declare module.exports: $Exports<'jquery-ui/ui/form'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-af.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-af'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ar-DZ.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ar-DZ'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ar.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ar'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-az.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-az'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-be.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-be'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-bg.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-bg'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-bs.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-bs'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ca.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ca'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-cs.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-cs'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-cy-GB.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-cy-GB'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-da.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-da'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-de.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-de'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-el.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-el'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-en-AU.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-en-AU'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-en-GB.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-en-GB'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-en-NZ.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-en-NZ'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-eo.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-eo'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-es.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-es'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-et.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-et'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-eu.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-eu'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-fa.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-fa'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-fi.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-fi'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-fo.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-fo'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-fr-CA.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-fr-CA'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-fr-CH.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-fr-CH'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-fr.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-fr'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-gl.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-gl'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-he.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-he'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-hi.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-hi'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-hr.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-hr'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-hu.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-hu'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-hy.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-hy'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-id.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-id'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-is.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-is'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-it-CH.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-it-CH'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-it.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-it'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ja.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ja'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ka.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ka'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-kk.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-kk'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-km.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-km'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ko.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ko'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ky.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ky'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-lb.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-lb'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-lt.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-lt'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-lv.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-lv'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-mk.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-mk'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ml.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ml'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ms.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ms'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-nb.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-nb'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-nl-BE.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-nl-BE'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-nl.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-nl'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-nn.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-nn'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-no.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-no'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-pl.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-pl'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-pt-BR.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-pt-BR'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-pt.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-pt'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-rm.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-rm'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ro.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ro'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ru.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ru'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-sk.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-sk'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-sl.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-sl'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-sq.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-sq'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-sr-SR.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-sr-SR'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-sr.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-sr'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-sv.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-sv'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-ta.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-ta'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-th.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-th'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-tj.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-tj'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-tr.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-tr'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-uk.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-uk'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-vi.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-vi'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-zh-CN.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-zh-CN'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-zh-HK.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-zh-HK'>;
}
declare module 'jquery-ui/ui/i18n/datepicker-zh-TW.js' {
  declare module.exports: $Exports<'jquery-ui/ui/i18n/datepicker-zh-TW'>;
}
declare module 'jquery-ui/ui/ie.js' {
  declare module.exports: $Exports<'jquery-ui/ui/ie'>;
}
declare module 'jquery-ui/ui/jquery-1-7.js' {
  declare module.exports: $Exports<'jquery-ui/ui/jquery-1-7'>;
}
declare module 'jquery-ui/ui/keycode.js' {
  declare module.exports: $Exports<'jquery-ui/ui/keycode'>;
}
declare module 'jquery-ui/ui/labels.js' {
  declare module.exports: $Exports<'jquery-ui/ui/labels'>;
}
declare module 'jquery-ui/ui/plugin.js' {
  declare module.exports: $Exports<'jquery-ui/ui/plugin'>;
}
declare module 'jquery-ui/ui/position.js' {
  declare module.exports: $Exports<'jquery-ui/ui/position'>;
}
declare module 'jquery-ui/ui/safe-active-element.js' {
  declare module.exports: $Exports<'jquery-ui/ui/safe-active-element'>;
}
declare module 'jquery-ui/ui/safe-blur.js' {
  declare module.exports: $Exports<'jquery-ui/ui/safe-blur'>;
}
declare module 'jquery-ui/ui/scroll-parent.js' {
  declare module.exports: $Exports<'jquery-ui/ui/scroll-parent'>;
}
declare module 'jquery-ui/ui/tabbable.js' {
  declare module.exports: $Exports<'jquery-ui/ui/tabbable'>;
}
declare module 'jquery-ui/ui/unique-id.js' {
  declare module.exports: $Exports<'jquery-ui/ui/unique-id'>;
}
declare module 'jquery-ui/ui/version.js' {
  declare module.exports: $Exports<'jquery-ui/ui/version'>;
}
declare module 'jquery-ui/ui/widget.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widget'>;
}
declare module 'jquery-ui/ui/widgets/accordion.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/accordion'>;
}
declare module 'jquery-ui/ui/widgets/autocomplete.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/autocomplete'>;
}
declare module 'jquery-ui/ui/widgets/button.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/button'>;
}
declare module 'jquery-ui/ui/widgets/checkboxradio.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/checkboxradio'>;
}
declare module 'jquery-ui/ui/widgets/controlgroup.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/controlgroup'>;
}
declare module 'jquery-ui/ui/widgets/datepicker.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/datepicker'>;
}
declare module 'jquery-ui/ui/widgets/dialog.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/dialog'>;
}
declare module 'jquery-ui/ui/widgets/draggable.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/draggable'>;
}
declare module 'jquery-ui/ui/widgets/droppable.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/droppable'>;
}
declare module 'jquery-ui/ui/widgets/menu.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/menu'>;
}
declare module 'jquery-ui/ui/widgets/mouse.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/mouse'>;
}
declare module 'jquery-ui/ui/widgets/progressbar.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/progressbar'>;
}
declare module 'jquery-ui/ui/widgets/resizable.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/resizable'>;
}
declare module 'jquery-ui/ui/widgets/selectable.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/selectable'>;
}
declare module 'jquery-ui/ui/widgets/selectmenu.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/selectmenu'>;
}
declare module 'jquery-ui/ui/widgets/slider.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/slider'>;
}
declare module 'jquery-ui/ui/widgets/sortable.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/sortable'>;
}
declare module 'jquery-ui/ui/widgets/spinner.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/spinner'>;
}
declare module 'jquery-ui/ui/widgets/tabs.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/tabs'>;
}
declare module 'jquery-ui/ui/widgets/tooltip.js' {
  declare module.exports: $Exports<'jquery-ui/ui/widgets/tooltip'>;
}
