// flow-typed signature: 9a0ba16ced5294f211bcda2543dc50f0
// flow-typed version: <<STUB>>/karma-jquery_v^0.2.3/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-jquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-jquery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-jquery/jquery/jquery-1.10.0' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.10.1' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.10.2' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.11.0' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.11.1' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.11.2' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.11.3' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.12.4' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.6.4' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.7.2' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.8.2' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.8.3' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.9.0' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-1.9.1' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.0.0' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.0.1' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.0.2' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.0.3' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.1.0' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.1.1' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.1.2' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.1.3' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.1.4' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.2.0' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.2.1' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.2.2' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.2.3' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-2.2.4' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-3.0.0' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-3.1.0' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-3.1.1' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-3.2.1' {
  declare module.exports: any;
}

declare module 'karma-jquery/jquery/jquery-3.3.1' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-jquery/index' {
  declare module.exports: $Exports<'karma-jquery'>;
}
declare module 'karma-jquery/index.js' {
  declare module.exports: $Exports<'karma-jquery'>;
}
declare module 'karma-jquery/jquery/jquery-1.10.0.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.10.0'>;
}
declare module 'karma-jquery/jquery/jquery-1.10.1.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.10.1'>;
}
declare module 'karma-jquery/jquery/jquery-1.10.2.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.10.2'>;
}
declare module 'karma-jquery/jquery/jquery-1.11.0.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.11.0'>;
}
declare module 'karma-jquery/jquery/jquery-1.11.1.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.11.1'>;
}
declare module 'karma-jquery/jquery/jquery-1.11.2.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.11.2'>;
}
declare module 'karma-jquery/jquery/jquery-1.11.3.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.11.3'>;
}
declare module 'karma-jquery/jquery/jquery-1.12.4.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.12.4'>;
}
declare module 'karma-jquery/jquery/jquery-1.6.4.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.6.4'>;
}
declare module 'karma-jquery/jquery/jquery-1.7.2.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.7.2'>;
}
declare module 'karma-jquery/jquery/jquery-1.8.2.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.8.2'>;
}
declare module 'karma-jquery/jquery/jquery-1.8.3.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.8.3'>;
}
declare module 'karma-jquery/jquery/jquery-1.9.0.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.9.0'>;
}
declare module 'karma-jquery/jquery/jquery-1.9.1.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-1.9.1'>;
}
declare module 'karma-jquery/jquery/jquery-2.0.0.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.0.0'>;
}
declare module 'karma-jquery/jquery/jquery-2.0.1.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.0.1'>;
}
declare module 'karma-jquery/jquery/jquery-2.0.2.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.0.2'>;
}
declare module 'karma-jquery/jquery/jquery-2.0.3.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.0.3'>;
}
declare module 'karma-jquery/jquery/jquery-2.1.0.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.1.0'>;
}
declare module 'karma-jquery/jquery/jquery-2.1.1.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.1.1'>;
}
declare module 'karma-jquery/jquery/jquery-2.1.2.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.1.2'>;
}
declare module 'karma-jquery/jquery/jquery-2.1.3.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.1.3'>;
}
declare module 'karma-jquery/jquery/jquery-2.1.4.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.1.4'>;
}
declare module 'karma-jquery/jquery/jquery-2.2.0.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.2.0'>;
}
declare module 'karma-jquery/jquery/jquery-2.2.1.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.2.1'>;
}
declare module 'karma-jquery/jquery/jquery-2.2.2.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.2.2'>;
}
declare module 'karma-jquery/jquery/jquery-2.2.3.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.2.3'>;
}
declare module 'karma-jquery/jquery/jquery-2.2.4.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-2.2.4'>;
}
declare module 'karma-jquery/jquery/jquery-3.0.0.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-3.0.0'>;
}
declare module 'karma-jquery/jquery/jquery-3.1.0.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-3.1.0'>;
}
declare module 'karma-jquery/jquery/jquery-3.1.1.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-3.1.1'>;
}
declare module 'karma-jquery/jquery/jquery-3.2.1.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-3.2.1'>;
}
declare module 'karma-jquery/jquery/jquery-3.3.1.js' {
  declare module.exports: $Exports<'karma-jquery/jquery/jquery-3.3.1'>;
}
