// flow-typed signature: a30526fe6aa527638f8a89d442f1198b
// flow-typed version: <<STUB>>/karma-fixture_v^0.2.6/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-fixture'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-fixture' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-fixture/lib/adapter' {
  declare module.exports: any;
}

declare module 'karma-fixture/lib/fixture' {
  declare module.exports: any;
}

declare module 'karma-fixture/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-fixture/lib/adapter.js' {
  declare module.exports: $Exports<'karma-fixture/lib/adapter'>;
}
declare module 'karma-fixture/lib/fixture.js' {
  declare module.exports: $Exports<'karma-fixture/lib/fixture'>;
}
declare module 'karma-fixture/lib/index.js' {
  declare module.exports: $Exports<'karma-fixture/lib/index'>;
}
