// flow-typed signature: 0d555e862d3f6c3494a1ff41dbaac9af
// flow-typed version: <<STUB>>/karma-jasmine-jquery_v^0.1.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-jasmine-jquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-jasmine-jquery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-jasmine-jquery/install' {
  declare module.exports: any;
}

declare module 'karma-jasmine-jquery/lib/index' {
  declare module.exports: any;
}

declare module 'karma-jasmine-jquery/lib/jasmine-jquery' {
  declare module.exports: any;
}

declare module 'karma-jasmine-jquery/lib/jasmine' {
  declare module.exports: any;
}

declare module 'karma-jasmine-jquery/lib/jqueryForJasmineJqueryPlugin' {
  declare module.exports: any;
}

declare module 'karma-jasmine-jquery/lib/saveCurrentJquery' {
  declare module.exports: any;
}

declare module 'karma-jasmine-jquery/lib/setJqueryForJasminJqueryPlugin' {
  declare module.exports: any;
}

declare module 'karma-jasmine-jquery/scripts/JasmineJqueryPluginPostInstallScript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-jasmine-jquery/install.js' {
  declare module.exports: $Exports<'karma-jasmine-jquery/install'>;
}
declare module 'karma-jasmine-jquery/lib/index.js' {
  declare module.exports: $Exports<'karma-jasmine-jquery/lib/index'>;
}
declare module 'karma-jasmine-jquery/lib/jasmine-jquery.js' {
  declare module.exports: $Exports<'karma-jasmine-jquery/lib/jasmine-jquery'>;
}
declare module 'karma-jasmine-jquery/lib/jasmine.js' {
  declare module.exports: $Exports<'karma-jasmine-jquery/lib/jasmine'>;
}
declare module 'karma-jasmine-jquery/lib/jqueryForJasmineJqueryPlugin.js' {
  declare module.exports: $Exports<'karma-jasmine-jquery/lib/jqueryForJasmineJqueryPlugin'>;
}
declare module 'karma-jasmine-jquery/lib/saveCurrentJquery.js' {
  declare module.exports: $Exports<'karma-jasmine-jquery/lib/saveCurrentJquery'>;
}
declare module 'karma-jasmine-jquery/lib/setJqueryForJasminJqueryPlugin.js' {
  declare module.exports: $Exports<'karma-jasmine-jquery/lib/setJqueryForJasminJqueryPlugin'>;
}
declare module 'karma-jasmine-jquery/scripts/JasmineJqueryPluginPostInstallScript.js' {
  declare module.exports: $Exports<'karma-jasmine-jquery/scripts/JasmineJqueryPluginPostInstallScript'>;
}
