// flow-typed signature: cce21cae3769353da26026f8f59ebbf5
// flow-typed version: <<STUB>>/redux-api-middleware_v^3.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-api-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-api-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-api-middleware/es/errors' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/es/errors.test' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/es/index' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/es/middleware' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/es/middleware.test' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/es/RSAA' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/es/util' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/es/util.test' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/es/validation' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/es/validation.test' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/lib/index.cjs' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/lib/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-api-middleware/es/errors.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/errors'>;
}
declare module 'redux-api-middleware/es/errors.test.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/errors.test'>;
}
declare module 'redux-api-middleware/es/index.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/index'>;
}
declare module 'redux-api-middleware/es/middleware.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/middleware'>;
}
declare module 'redux-api-middleware/es/middleware.test.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/middleware.test'>;
}
declare module 'redux-api-middleware/es/RSAA.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/RSAA'>;
}
declare module 'redux-api-middleware/es/util.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/util'>;
}
declare module 'redux-api-middleware/es/util.test.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/util.test'>;
}
declare module 'redux-api-middleware/es/validation.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/validation'>;
}
declare module 'redux-api-middleware/es/validation.test.js' {
  declare module.exports: $Exports<'redux-api-middleware/es/validation.test'>;
}
declare module 'redux-api-middleware/lib/index.cjs.js' {
  declare module.exports: $Exports<'redux-api-middleware/lib/index.cjs'>;
}
declare module 'redux-api-middleware/lib/index.umd.js' {
  declare module.exports: $Exports<'redux-api-middleware/lib/index.umd'>;
}
