// flow-typed signature: 9e2139c5a0262c28e8c26ca1b6f434b2
// flow-typed version: <<STUB>>/redux-immutable-state-invariant_v^2.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-immutable-state-invariant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-immutable-state-invariant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-immutable-state-invariant/dist/index' {
  declare module.exports: any;
}

declare module 'redux-immutable-state-invariant/dist/isImmutable' {
  declare module.exports: any;
}

declare module 'redux-immutable-state-invariant/dist/trackForMutations' {
  declare module.exports: any;
}

declare module 'redux-immutable-state-invariant/example/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-immutable-state-invariant/dist/index.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/dist/index'>;
}
declare module 'redux-immutable-state-invariant/dist/isImmutable.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/dist/isImmutable'>;
}
declare module 'redux-immutable-state-invariant/dist/trackForMutations.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/dist/trackForMutations'>;
}
declare module 'redux-immutable-state-invariant/example/webpack.config.js' {
  declare module.exports: $Exports<'redux-immutable-state-invariant/example/webpack.config'>;
}
