// flow-typed signature: 99526e13b57fb8f19e7072382dfa954c
// flow-typed version: <<STUB>>/replace_v^1.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'replace/bin/parse-arguments' {
  declare module.exports: any;
}

declare module 'replace/bin/replace' {
  declare module.exports: any;
}

declare module 'replace/bin/search' {
  declare module.exports: any;
}

declare module 'replace/bin/shared-options' {
  declare module.exports: any;
}

declare module 'replace/replace' {
  declare module.exports: any;
}

declare module 'replace/test/paths' {
  declare module.exports: any;
}

declare module 'replace/test/sanity' {
  declare module.exports: any;
}

declare module 'replace/testfunc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'replace/bin/parse-arguments.js' {
  declare module.exports: $Exports<'replace/bin/parse-arguments'>;
}
declare module 'replace/bin/replace.js' {
  declare module.exports: $Exports<'replace/bin/replace'>;
}
declare module 'replace/bin/search.js' {
  declare module.exports: $Exports<'replace/bin/search'>;
}
declare module 'replace/bin/shared-options.js' {
  declare module.exports: $Exports<'replace/bin/shared-options'>;
}
declare module 'replace/replace.js' {
  declare module.exports: $Exports<'replace/replace'>;
}
declare module 'replace/test/paths.js' {
  declare module.exports: $Exports<'replace/test/paths'>;
}
declare module 'replace/test/sanity.js' {
  declare module.exports: $Exports<'replace/test/sanity'>;
}
declare module 'replace/testfunc.js' {
  declare module.exports: $Exports<'replace/testfunc'>;
}
