// flow-typed signature: c13c5465f62c7716e219b8eb7d33f12e
// flow-typed version: <<STUB>>/url-polyfill_v^1.1.3/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-polyfill/do-not-use/url' {
  declare module.exports: any;
}

declare module 'url-polyfill/tests/classes/Async' {
  declare module.exports: any;
}

declare module 'url-polyfill/tests/classes/Driver' {
  declare module.exports: any;
}

declare module 'url-polyfill/tests/classes/Tester' {
  declare module.exports: any;
}

declare module 'url-polyfill/tests/test-url-class' {
  declare module.exports: any;
}

declare module 'url-polyfill/tests/test' {
  declare module.exports: any;
}

declare module 'url-polyfill/tests/url-poly' {
  declare module.exports: any;
}

declare module 'url-polyfill/url-polyfill' {
  declare module.exports: any;
}

declare module 'url-polyfill/url-polyfill.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-polyfill/do-not-use/url.js' {
  declare module.exports: $Exports<'url-polyfill/do-not-use/url'>;
}
declare module 'url-polyfill/tests/classes/Async.js' {
  declare module.exports: $Exports<'url-polyfill/tests/classes/Async'>;
}
declare module 'url-polyfill/tests/classes/Driver.js' {
  declare module.exports: $Exports<'url-polyfill/tests/classes/Driver'>;
}
declare module 'url-polyfill/tests/classes/Tester.js' {
  declare module.exports: $Exports<'url-polyfill/tests/classes/Tester'>;
}
declare module 'url-polyfill/tests/test-url-class.js' {
  declare module.exports: $Exports<'url-polyfill/tests/test-url-class'>;
}
declare module 'url-polyfill/tests/test.js' {
  declare module.exports: $Exports<'url-polyfill/tests/test'>;
}
declare module 'url-polyfill/tests/url-poly.js' {
  declare module.exports: $Exports<'url-polyfill/tests/url-poly'>;
}
declare module 'url-polyfill/url-polyfill.js' {
  declare module.exports: $Exports<'url-polyfill/url-polyfill'>;
}
declare module 'url-polyfill/url-polyfill.min.js' {
  declare module.exports: $Exports<'url-polyfill/url-polyfill.min'>;
}
