// flow-typed signature: d8ba36dd5402cb064e59f5d67ae4602e
// flow-typed version: <<STUB>>/virtual-dom_v^2.1.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'virtual-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'virtual-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'virtual-dom/create-element' {
  declare module.exports: any;
}

declare module 'virtual-dom/diff' {
  declare module.exports: any;
}

declare module 'virtual-dom/dist/virtual-dom' {
  declare module.exports: any;
}

declare module 'virtual-dom/h' {
  declare module.exports: any;
}

declare module 'virtual-dom/patch' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/attributes' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/hook' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/index' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/keys' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/lib/assert-childNodes-from-array' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/lib/assert-equal-dom' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/lib/nodes-from-array' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/lib/patch-count' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/main' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/nested-properties' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/non-string' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/sort' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/style' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/thunk' {
  declare module.exports: any;
}

declare module 'virtual-dom/test/undefined-properties' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/apply-properties' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/create-element' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/dom-index' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/patch-op' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/patch' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/test/dom-index' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/test/index' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/test/patch-index' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/test/patch-op-index' {
  declare module.exports: any;
}

declare module 'virtual-dom/vdom/update-widget' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/hooks/attribute-hook' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/hooks/ev-hook' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/hooks/focus-hook' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/hooks/soft-set-hook' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/index' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/parse-tag' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/svg-attribute-namespace' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/svg' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/test/attribute-hook' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/test/ev-hook' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/test/h' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/test/index' {
  declare module.exports: any;
}

declare module 'virtual-dom/virtual-hyperscript/test/svg' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/handle-thunk' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/is-thunk' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/is-vhook' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/is-vnode' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/is-vtext' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/is-widget' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/test/handle-thunk' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/test/index' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/version' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/vnode' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/vpatch' {
  declare module.exports: any;
}

declare module 'virtual-dom/vnode/vtext' {
  declare module.exports: any;
}

declare module 'virtual-dom/vtree/diff-props' {
  declare module.exports: any;
}

declare module 'virtual-dom/vtree/diff' {
  declare module.exports: any;
}

declare module 'virtual-dom/vtree/test/diff-props' {
  declare module.exports: any;
}

declare module 'virtual-dom/vtree/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'virtual-dom/create-element.js' {
  declare module.exports: $Exports<'virtual-dom/create-element'>;
}
declare module 'virtual-dom/diff.js' {
  declare module.exports: $Exports<'virtual-dom/diff'>;
}
declare module 'virtual-dom/dist/virtual-dom.js' {
  declare module.exports: $Exports<'virtual-dom/dist/virtual-dom'>;
}
declare module 'virtual-dom/h.js' {
  declare module.exports: $Exports<'virtual-dom/h'>;
}
declare module 'virtual-dom/index' {
  declare module.exports: $Exports<'virtual-dom'>;
}
declare module 'virtual-dom/index.js' {
  declare module.exports: $Exports<'virtual-dom'>;
}
declare module 'virtual-dom/patch.js' {
  declare module.exports: $Exports<'virtual-dom/patch'>;
}
declare module 'virtual-dom/test/attributes.js' {
  declare module.exports: $Exports<'virtual-dom/test/attributes'>;
}
declare module 'virtual-dom/test/hook.js' {
  declare module.exports: $Exports<'virtual-dom/test/hook'>;
}
declare module 'virtual-dom/test/index.js' {
  declare module.exports: $Exports<'virtual-dom/test/index'>;
}
declare module 'virtual-dom/test/keys.js' {
  declare module.exports: $Exports<'virtual-dom/test/keys'>;
}
declare module 'virtual-dom/test/lib/assert-childNodes-from-array.js' {
  declare module.exports: $Exports<'virtual-dom/test/lib/assert-childNodes-from-array'>;
}
declare module 'virtual-dom/test/lib/assert-equal-dom.js' {
  declare module.exports: $Exports<'virtual-dom/test/lib/assert-equal-dom'>;
}
declare module 'virtual-dom/test/lib/nodes-from-array.js' {
  declare module.exports: $Exports<'virtual-dom/test/lib/nodes-from-array'>;
}
declare module 'virtual-dom/test/lib/patch-count.js' {
  declare module.exports: $Exports<'virtual-dom/test/lib/patch-count'>;
}
declare module 'virtual-dom/test/main.js' {
  declare module.exports: $Exports<'virtual-dom/test/main'>;
}
declare module 'virtual-dom/test/nested-properties.js' {
  declare module.exports: $Exports<'virtual-dom/test/nested-properties'>;
}
declare module 'virtual-dom/test/non-string.js' {
  declare module.exports: $Exports<'virtual-dom/test/non-string'>;
}
declare module 'virtual-dom/test/sort.js' {
  declare module.exports: $Exports<'virtual-dom/test/sort'>;
}
declare module 'virtual-dom/test/style.js' {
  declare module.exports: $Exports<'virtual-dom/test/style'>;
}
declare module 'virtual-dom/test/thunk.js' {
  declare module.exports: $Exports<'virtual-dom/test/thunk'>;
}
declare module 'virtual-dom/test/undefined-properties.js' {
  declare module.exports: $Exports<'virtual-dom/test/undefined-properties'>;
}
declare module 'virtual-dom/vdom/apply-properties.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/apply-properties'>;
}
declare module 'virtual-dom/vdom/create-element.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/create-element'>;
}
declare module 'virtual-dom/vdom/dom-index.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/dom-index'>;
}
declare module 'virtual-dom/vdom/patch-op.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/patch-op'>;
}
declare module 'virtual-dom/vdom/patch.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/patch'>;
}
declare module 'virtual-dom/vdom/test/dom-index.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/test/dom-index'>;
}
declare module 'virtual-dom/vdom/test/index.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/test/index'>;
}
declare module 'virtual-dom/vdom/test/patch-index.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/test/patch-index'>;
}
declare module 'virtual-dom/vdom/test/patch-op-index.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/test/patch-op-index'>;
}
declare module 'virtual-dom/vdom/update-widget.js' {
  declare module.exports: $Exports<'virtual-dom/vdom/update-widget'>;
}
declare module 'virtual-dom/virtual-hyperscript/hooks/attribute-hook.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/hooks/attribute-hook'>;
}
declare module 'virtual-dom/virtual-hyperscript/hooks/ev-hook.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/hooks/ev-hook'>;
}
declare module 'virtual-dom/virtual-hyperscript/hooks/focus-hook.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/hooks/focus-hook'>;
}
declare module 'virtual-dom/virtual-hyperscript/hooks/soft-set-hook.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/hooks/soft-set-hook'>;
}
declare module 'virtual-dom/virtual-hyperscript/index.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/index'>;
}
declare module 'virtual-dom/virtual-hyperscript/parse-tag.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/parse-tag'>;
}
declare module 'virtual-dom/virtual-hyperscript/svg-attribute-namespace.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/svg-attribute-namespace'>;
}
declare module 'virtual-dom/virtual-hyperscript/svg.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/svg'>;
}
declare module 'virtual-dom/virtual-hyperscript/test/attribute-hook.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/test/attribute-hook'>;
}
declare module 'virtual-dom/virtual-hyperscript/test/ev-hook.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/test/ev-hook'>;
}
declare module 'virtual-dom/virtual-hyperscript/test/h.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/test/h'>;
}
declare module 'virtual-dom/virtual-hyperscript/test/index.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/test/index'>;
}
declare module 'virtual-dom/virtual-hyperscript/test/svg.js' {
  declare module.exports: $Exports<'virtual-dom/virtual-hyperscript/test/svg'>;
}
declare module 'virtual-dom/vnode/handle-thunk.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/handle-thunk'>;
}
declare module 'virtual-dom/vnode/is-thunk.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/is-thunk'>;
}
declare module 'virtual-dom/vnode/is-vhook.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/is-vhook'>;
}
declare module 'virtual-dom/vnode/is-vnode.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/is-vnode'>;
}
declare module 'virtual-dom/vnode/is-vtext.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/is-vtext'>;
}
declare module 'virtual-dom/vnode/is-widget.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/is-widget'>;
}
declare module 'virtual-dom/vnode/test/handle-thunk.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/test/handle-thunk'>;
}
declare module 'virtual-dom/vnode/test/index.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/test/index'>;
}
declare module 'virtual-dom/vnode/version.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/version'>;
}
declare module 'virtual-dom/vnode/vnode.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/vnode'>;
}
declare module 'virtual-dom/vnode/vpatch.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/vpatch'>;
}
declare module 'virtual-dom/vnode/vtext.js' {
  declare module.exports: $Exports<'virtual-dom/vnode/vtext'>;
}
declare module 'virtual-dom/vtree/diff-props.js' {
  declare module.exports: $Exports<'virtual-dom/vtree/diff-props'>;
}
declare module 'virtual-dom/vtree/diff.js' {
  declare module.exports: $Exports<'virtual-dom/vtree/diff'>;
}
declare module 'virtual-dom/vtree/test/diff-props.js' {
  declare module.exports: $Exports<'virtual-dom/vtree/test/diff-props'>;
}
declare module 'virtual-dom/vtree/test/index.js' {
  declare module.exports: $Exports<'virtual-dom/vtree/test/index'>;
}
