default: &DEFAULT
  access_key_id:     "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  bucket:            "<%= ENV['AWS_BUCKET'] %>"
  region:            "<%= ENV['AWS_REGION'] %>"
  hostname:          "<%= ENV['AWS_HOSTNAME'] %>"
  protocol:          "<%= ENV['AWS_PROTOCOL'] %>"
  force_path_style:  <%= ENV['AWS_PATH_STYLE'].presence || false %>

production:
 <<: *DEFAULT

preview:
 <<: *DEFAULT
