default: &DEFAULT
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  role_arn: "<%= ENV['AWS_ROLE_ARN'] %>"
  web_identity_token_file: "<%= ENV['AWS_WEB_IDENTITY_TOKEN_FILE'] %>"
  bucket: "<%= ENV['AWS_BUCKET'] %>"
  region: "<%= ENV['AWS_REGION'] %>"
  hostname: "<%= ENV['AWS_HOSTNAME'] %>"
  protocol: "<%= ENV['AWS_PROTOCOL'] %>"
  force_path_style: <%= ENV['AWS_PATH_STYLE'].presence || false %>

production:
 <<: *DEFAULT

preview:
 <<: *DEFAULT
