development:
  - :mem_cache_store
  - <%= ENV.fetch('MEMCACHE_SERVERS', nil) %>

test:
  - :null_store

preview:
  - :mem_cache_store
  - <%= ENV.fetch('MEMCACHE_SERVERS', nil) %>

production:
  - :mem_cache_store
  - <%= ENV.fetch('MEMCACHE_SERVERS', nil) %>
