base: &default

<% case ENV['DATABASE_URL'].to_s
   when /^oracle/ %>
  adapter: oracle_enhanced
  time_zone: 'UTC'
  statement_limit: <%= ENV.fetch('ORACLE_STATEMENT_LIMIT', 250) %>
<% when /^postgresql/ %>
  adapter: postgresql
  variables:
    timezone: 'UTC'
<% else %>
  adapter: mysql2
<% end %>

  url: <%= ENV['DATABASE_URL'] %>
  encoding: utf8
  collation: utf8_bin
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

production:
  <<: *default

preview:
  <<: *default

development:
  <<: *default
