base: &default
  enabled: true
  redis:
    url: <%= ENV.fetch('MESSAGE_BUS_REDIS_URL', 'redis://system-redis:6379/8') %>
    pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
    pool_timeout: 5
    namespace:

production:
  <<: *default

preview:
  <<: *default

development:
  <<: *default
