default: &base
  enabled: false
  server_scheme: 'https'
  server_port: 8443
  authentication_method: service_account

development:
  <<: *base
  server_host:
  bearer_token:

test:
  <<: *base
  server_host:
  bearer_token:

production:
  <<: *base
  server_host:
  bearer_token:

preview:
  <<: *base
  server_host:
  bearer_token:
