default: &base
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

development:
  <<: *base

test:
  <<: *base

# Do not keep preview secrets in the repository,
# instead read values from the environment.
preview:
  <<: *base

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *base
