default: &base
  enabled: true
  server_scheme: 'https'
  server_host: 'kubernetes.default.svc.cluster.local'
  server_port: 443

production:
  <<: *base
  bearer_token: "<%= ENV['KUBERNETES_BEARER_TOKEN'] %>"

preview:
  <<: *base
  bearer_token: "<%= ENV['KUBERNETES_BEARER_TOKEN'] %>"
