base: &default
  address: <%= ENV['SMTP_ADDRESS'] %>
  port: <%= ENV.fetch('SMTP_PORT', '25').to_i %>
  domain: <%= ENV['THREESCALE_SUPERDOMAIN'] || 'localhost' %>
  authentication: <%= ENV['SMTP_AUTHENTICATION'] || 'plain' %>
  enable_starttls_auto: <%= ENV.fetch('SMTP_STARTTLS_AUTO', '1') == '1' %>
  openssl_verify_mode: <%= ENV['SMTP_OPENSSL_VERIFY_MODE'] || 'none' %>
  user_name: <%= ENV['SMTP_USER_NAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>

production:
  <<: *default

preview:
  <<: *default

