eval_gemfile '../../Gemfile.base'

source 'https://gems.contribsys.com/' do
  gem 'sidekiq-pro', '~> 3.4', require: %w(sidekiq-pro sidekiq/pro/web)
end

# one of the license terms does not permit modifications and presents unclear risk to redhat
gem 'airbrake', '~> 4.3.3'

# one of the license terms does not permit modifications and presents unclear risk to redhat
# NewRelic RPM
# docs says it should be loaded latest as possible
group :production, :preview, :development do
  gem 'newrelic_rpm', '~> 5.6'
end

