# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

default: &base
  support_provider_key: <%= ENV['SUPPORT_PROVIDER_KEY'] %>
  support_provider_key_preview: <%= ENV['SUPPORT_PROVIDER_KEY_PREVIEW'] %>

development:
  <<: *base
  secret_key_base: '5ceba390bc5ae45231c8c7fc6068cddd623fe3c92bca569cab9db110d2523fed61684932d33ff22f0bc067170065eb47c92343f5080d1c4af7912bb323025236'

test:
  <<: *base
  secret_key_base: '2cd671bcb3ecacd9f757989a709077142e582380f2f0f85b91593d2afa4aa3aa4c1faaf2c8fc68230bbd1b5028533d84531e2e394ed71485dfc94fde29a3e5cf'

# Do not keep preview secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `preview:` environment over there.
preview:
  <<: *base
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
production:
  <<: *base
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
