default: &base
  support_provider_key: <%= ENV['SUPPORT_PROVIDER_KEY'] %>
  support_provider_key_preview: <%= ENV['SUPPORT_PROVIDER_KEY_PREVIEW'] %>

development:
  <<: *base
  secret_key_base: '5ceba390bc5ae45231c8c7fc6068cddd623fe3c92bca569cab9db110d2523fed61684932d33ff22f0bc067170065eb47c92343f5080d1c4af7912bb323025236'

test:
  <<: *base
  secret_key_base: '2cd671bcb3ecacd9f757989a709077142e582380f2f0f85b91593d2afa4aa3aa4c1faaf2c8fc68230bbd1b5028533d84531e2e394ed71485dfc94fde29a3e5cf'

# Do not keep preview secrets in the repository,
# instead read values from the environment.
preview:
  <<: *base
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *base
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
