base: &default
  endpoint: <%= ENV['ZYNC_ENDPOINT'] %>
  authentication:
    token: <%= ENV['ZYNC_AUTHENTICATION_TOKEN'] %>
  connect_timeout: 2
  send_timeout: 2
  receive_timeout: 10
  skip_non_oidc_applications: false

development:
  <<: *default

test:
  <<: *default
  endpoint:

production:
  <<: *default
