// flow-typed signature: ec984c80a93f542ae67455f74a4df1b0
// flow-typed version: <<STUB>>/@rails/webpacker_v^3.5.5/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rails/webpacker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rails/webpacker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rails/webpacker/package/__tests__/config' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/__tests__/dev_server' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/__tests__/development' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/__tests__/env' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/__tests__/production' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/__tests__/staging' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/__tests__/test' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/config_types/__tests__/config_list' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/config_types/__tests__/config_object' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/config_types/config_list' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/config_types/config_object' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/config_types/index' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/config' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/dev_server' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/env' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/environments/__tests__/base' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/environments/base' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/environments/development' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/environments/production' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/environments/test' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/index' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/rules/babel' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/rules/css' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/rules/file' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/rules/index' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/rules/module.css' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/rules/module.sass' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/rules/sass' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/utils/__tests__/deep_assign' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/utils/__tests__/deep_merge' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/utils/__tests__/get_style_rule' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/utils/__tests__/objectify' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/utils/deep_assign' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/utils/deep_merge' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/utils/get_style_rule' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/utils/helpers' {
  declare module.exports: any;
}

declare module '@rails/webpacker/package/utils/objectify' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rails/webpacker/package/__tests__/config.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/__tests__/config'>;
}
declare module '@rails/webpacker/package/__tests__/dev_server.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/__tests__/dev_server'>;
}
declare module '@rails/webpacker/package/__tests__/development.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/__tests__/development'>;
}
declare module '@rails/webpacker/package/__tests__/env.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/__tests__/env'>;
}
declare module '@rails/webpacker/package/__tests__/production.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/__tests__/production'>;
}
declare module '@rails/webpacker/package/__tests__/staging.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/__tests__/staging'>;
}
declare module '@rails/webpacker/package/__tests__/test.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/__tests__/test'>;
}
declare module '@rails/webpacker/package/config_types/__tests__/config_list.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/config_types/__tests__/config_list'>;
}
declare module '@rails/webpacker/package/config_types/__tests__/config_object.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/config_types/__tests__/config_object'>;
}
declare module '@rails/webpacker/package/config_types/config_list.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/config_types/config_list'>;
}
declare module '@rails/webpacker/package/config_types/config_object.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/config_types/config_object'>;
}
declare module '@rails/webpacker/package/config_types/index.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/config_types/index'>;
}
declare module '@rails/webpacker/package/config.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/config'>;
}
declare module '@rails/webpacker/package/dev_server.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/dev_server'>;
}
declare module '@rails/webpacker/package/env.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/env'>;
}
declare module '@rails/webpacker/package/environments/__tests__/base.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/environments/__tests__/base'>;
}
declare module '@rails/webpacker/package/environments/base.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/environments/base'>;
}
declare module '@rails/webpacker/package/environments/development.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/environments/development'>;
}
declare module '@rails/webpacker/package/environments/production.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/environments/production'>;
}
declare module '@rails/webpacker/package/environments/test.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/environments/test'>;
}
declare module '@rails/webpacker/package/index.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/index'>;
}
declare module '@rails/webpacker/package/rules/babel.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/rules/babel'>;
}
declare module '@rails/webpacker/package/rules/css.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/rules/css'>;
}
declare module '@rails/webpacker/package/rules/file.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/rules/file'>;
}
declare module '@rails/webpacker/package/rules/index.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/rules/index'>;
}
declare module '@rails/webpacker/package/rules/module.css.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/rules/module.css'>;
}
declare module '@rails/webpacker/package/rules/module.sass.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/rules/module.sass'>;
}
declare module '@rails/webpacker/package/rules/sass.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/rules/sass'>;
}
declare module '@rails/webpacker/package/utils/__tests__/deep_assign.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/utils/__tests__/deep_assign'>;
}
declare module '@rails/webpacker/package/utils/__tests__/deep_merge.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/utils/__tests__/deep_merge'>;
}
declare module '@rails/webpacker/package/utils/__tests__/get_style_rule.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/utils/__tests__/get_style_rule'>;
}
declare module '@rails/webpacker/package/utils/__tests__/objectify.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/utils/__tests__/objectify'>;
}
declare module '@rails/webpacker/package/utils/deep_assign.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/utils/deep_assign'>;
}
declare module '@rails/webpacker/package/utils/deep_merge.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/utils/deep_merge'>;
}
declare module '@rails/webpacker/package/utils/get_style_rule.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/utils/get_style_rule'>;
}
declare module '@rails/webpacker/package/utils/helpers.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/utils/helpers'>;
}
declare module '@rails/webpacker/package/utils/objectify.js' {
  declare module.exports: $Exports<'@rails/webpacker/package/utils/objectify'>;
}
