development:
  - :mem_cache_store
  - <%= ENV.fetch('MEMCACHE_SERVERS', 'localhost:11211') %>

test:
  - :null_store

preview:
  - :mem_cache_store
  - localhost:11211

production:
  - :mem_cache_store
  - localhost:11211
