base: &default
  url: "<%= File.join(ENV.fetch('BACKEND_URL', 'http://localhost:3001'), '/internal/') %>"
  fake_server: false
  username: <%= ENV.fetch('CONFIG_INTERNAL_API_USER', nil) %>
  password: <%= ENV.fetch('CONFIG_INTERNAL_API_PASSWORD', nil) %>

development:
  <<: *default
  # fake server is useful when you don't run a real backend apisonator
  # fake_server: 'http://localhost:3000/internal/'

test:
  <<: *default

production:
  <<: *default
  url: "<%= File.join(ENV.fetch('BACKEND_URL', 'http://backend-listener:3000'), '/internal/') %>"
