cors: &default
  enabled: false
  allow:
  - origins: '*'
    resources:
    - !ruby/regexp /\.(?:woff2?|otf|ttf|svg|eot)$/
    headers: 'x-requested-with'
    methods: :get
    max_age: 3628800
    credentials: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  enabled: true

preview:
  <<: *default
  enabled: true
