base: &default
  enabled: true

production:
  <<: *default
  redis:
    url: <%= ENV.fetch('MESSAGE_BUS_REDIS_URL', 'redis://localhost/8') %>
    pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
    pool_timeout: 5
    namespace: system-mbus

preview:
  <<: *default
  redis:
    url: <%= ENV.fetch('MESSAGE_BUS_REDIS_URL', 'redis://localhost/8') %>
    pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
    pool_timeout: 5
    namespace: system-mbus

development:
  <<: *default
  redis:
    url: <%= ENV.fetch('MESSAGE_BUS_REDIS_URL', 'redis://localhost/8') %>
    pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
    pool_timeout: 5
    namespace: system-mbus

test:
  enabled: false
  keepalive_interval: 0
  backend: :memory
