base: &default
  enabled: true
  redis:
    url: <%= ENV['MESSAGE_BUS_REDIS_URL'] %>
    pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
    pool_timeout: 5
    namespace: <%= ENV['MESSAGE_BUS_REDIS_NAMESPACE'] %>

production:
  <<: *default

preview:
  <<: *default

development:
  <<: *default
  keepalive_interval: 0

test:
  enabled: false
  keepalive_interval: 0
  backend: :memory
