base: &default
  github:
    enabled: <%= ENV.fetch('GITHUB_ENABLED', '1') == '1' %>
    client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>

development:
  <<: *default

test:
  github:
    enabled: true
    client_id: fake_id
    client_secret: fake_secret

production:
  <<: *default
