---
production:
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost/3') %>
  pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  pool_timeout: 5 # this is in seconds
  namespace: system-sidekiq
development:
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost/1') %>
  pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  pool_timeout: 5 # this is in seconds
  namespace: system-sidekiq
test:
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost/1') %>
  db: <%= 2 + ENV['TEST_ENV_NUMBER'].to_i %>
  pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  pool_timeout: 5 # this is in seconds
  namespace: system-sidekiq
