base: &base
  url: "<%= ENV.fetch('REDIS_URL', 'redis://localhost/1') %>"
  pool_size: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  pool_timeout: 5 # this is in seconds
  namespace: "<%= ENV['REDIS_NAMESPACE'] %>"
  sentinels: "<%= ENV['REDIS_SENTINEL_HOSTS'] %>"
  role: <%= ENV['REDIS_SENTINEL_ROLE'] %>

development:
  <<: *base

test:
  <<: *base
  db: <%= 2 + ENV['TEST_ENV_NUMBER'].to_i %>

production:
  <<: *base
  url: "<%= ENV.fetch('REDIS_URL', 'redis://localhost/3') %>"
