base: &default
  enabled: false
  stub: false
  write_key: 'null'

development:
  <<: *default

test:
  <<: *default
  enabled: false
  stub: true

preview:
  <<: *default

production:
  <<: *default
