base: &default
  enabled: <%= ENV['SEGMENT_WRITE_KEY'].present? %>
  write_key: <%= ENV['SEGMENT_WRITE_KEY'] %>

development:
  <<: *default

test:
  <<: *default
  stub: true

production:
  <<: *default
