# Additional info: https://docs.openshift.com/container-platform/4.9/web_console/creating-quick-start-tutorials.html
metadata:
  name: getting-started-with-quick-starts
  # you can add additional metadata here
  instructional: true
spec:
  displayName: Create an application
  durationMinutes: 5
  # Optional type section, will display as a tile on the card
  type: 
    text: Quick start
    # 'blue' | 'cyan' | 'green' | 'orange' | 'purple' | 'red' | 'grey'
    color: grey
  # - The icon defined as a base64 value. Example flow:
  # 1. Find an .svg you want to use, like from here: https://www.patternfly.org/v4/guidelines/icons/#all-icons
  # 2. Upload the file here and encode it (output format - plain text): https://base64.guru/converter/encode/image
  # 3. compose - `icon: data:image/svg+xml;base64,<base64 string from step 2>`
  # - If empty string (icon: ''), will use a default rocket icon
  # - If set to null (icon: ~) will not show an icon
  icon: data:image/svg+xml;base64,PCEtLSBHZW5lcmF0ZWQgYnkgSWNvTW9vbi5pbyAtLT4KPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjUxMiIgaGVpZ2h0PSI1MTIiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj4KPHRpdGxlPjwvdGl0bGU+CjxnIGlkPSJpY29tb29uLWlnbm9yZSI+CjwvZz4KPHBhdGggZD0iTTQ0OCA2NHY0MTZoLTMzNmMtMjYuNTEzIDAtNDgtMjEuNDktNDgtNDhzMjEuNDg3LTQ4IDQ4LTQ4aDMwNHYtMzg0aC0zMjBjLTM1LjE5OSAwLTY0IDI4LjgtNjQgNjR2Mzg0YzAgMzUuMiAyOC44MDEgNjQgNjQgNjRoMzg0di00NDhoLTMyeiI+PC9wYXRoPgo8cGF0aCBkPSJNMTEyLjAyOCA0MTZ2MGMtMC4wMDkgMC4wMDEtMC4wMTkgMC0wLjAyOCAwLTguODM2IDAtMTYgNy4xNjMtMTYgMTZzNy4xNjQgMTYgMTYgMTZjMC4wMDkgMCAwLjAxOS0wLjAwMSAwLjAyOC0wLjAwMXYwLjAwMWgzMDMuOTQ1di0zMmgtMzAzLjk0NXoiPjwvcGF0aD4KPC9zdmc+Cg==
  description: |-
    Subscribe to an application plan to obtain the key to call an API product.
  introduction: |-
    This quick start guides you to create an application to subscribe to an application plan in order to obtain the key to call an API product.
    
    To learn more about application plans, see the [3scale documentation](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.11/html/getting_started/first-steps-with-threescale_configuring-your-api#creating-applications-for-default-account-test-api-calls_configuring-your-api).
  tasks:
    - title: Create an application
      description: |-
        An application is always associated with an application plan.
        
        ### Procedure
        1. Navigate to <strong>Audience > Accounts > Listing</strong>.
        1. Click <strong>[Your_account]</strong>.
        1. Go to the _Application_ tab.
        1. Click <strong>Create application</strong>.
        1. On the _New application_ page, fill in the details.

          Important fields:
            - _Application plan_: An application is always associated with an application plan. If there is no existing application plan, click <strong>Create a new application plan</strong>.
        1. Click <strong>Create application</strong>

      # optional - the task's Check your work module
      review:
        instructions: |-
          - Have you associated your application with an existing application plan?
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      # optional - the task's success and failure messages
      summary:
        success: Shows a success message in the task header
        failed: Shows a failed message in the task header
  conclusion: |-
    This concludes the set up of your backend for 3scale.
  # you can link to the next quick start(s) here
  nextQuickStart:
    - mas-alert-note-prereq