# Additional info: https://docs.openshift.com/container-platform/4.9/web_console/creating-quick-start-tutorials.html
metadata:
  name: learning-about-application-plans
  category: 3scale API Management features
spec:
  displayName: Application plans
  durationMinutes: 5
 # Optional type section, will display as a tile on the card
  type:
    text: Tour
    # 'blue' | 'cyan' | 'green' | 'orange' | 'purple' | 'red' | 'grey'
    color: grey
  # - The icon defined as a base64 value. Example flow:
  # 1. Find an .svg you want to use, like from here: https://www.patternfly.org/v4/guidelines/icons/#all-icons
  # 2. Upload the file here and encode it (output format - plain text): https://base64.guru/converter/encode/image
  # 3. compose - `icon: data:image/svg+xml;base64,<base64 string from step 2>`
  # - If empty string (icon: ''), will use a default rocket icon
  # - If set to null (icon: ~) will not show an icon
  icon: data:image/svg+xml;base64,PCEtLSBHZW5lcmF0ZWQgYnkgSWNvTW9vbi5pbyAtLT4KPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjUxMiIgaGVpZ2h0PSI1MTIiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj4KPHRpdGxlPjwvdGl0bGU+CjxnIGlkPSJpY29tb29uLWlnbm9yZSI+CjwvZz4KPHBhdGggZD0iTTQ0OCA2NHY0MTZoLTMzNmMtMjYuNTEzIDAtNDgtMjEuNDktNDgtNDhzMjEuNDg3LTQ4IDQ4LTQ4aDMwNHYtMzg0aC0zMjBjLTM1LjE5OSAwLTY0IDI4LjgtNjQgNjR2Mzg0YzAgMzUuMiAyOC44MDEgNjQgNjQgNjRoMzg0di00NDhoLTMyeiI+PC9wYXRoPgo8cGF0aCBkPSJNMTEyLjAyOCA0MTZ2MGMtMC4wMDkgMC4wMDEtMC4wMTkgMC0wLjAyOCAwLTguODM2IDAtMTYgNy4xNjMtMTYgMTZzNy4xNjQgMTYgMTYgMTZjMC4wMDkgMCAwLjAxOS0wLjAwMSAwLjAyOC0wLjAwMXYwLjAwMWgzMDMuOTQ1di0zMmgtMzAzLjk0NXoiPjwvcGF0aD4KPC9zdmc+Cg==
  description: |-
    Learn about API contract.
  introduction: |-
    In this quick start, you will learn about application plans. To learn more, see the [3scale documentation](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.13/html/getting_started/first-steps-with-threescale_configuring-your-api#creating-threescale-application-plans-for-products_configuring-your-api).
  tasks:
    - title:  Learn about application plans
      description: |-

        An application plan is the API contract that establishes rules like access rights, limits, and pricing in response to an API consumer registered to use your API endpoint in the API package. In the Admin Portal, you must assign every API package to an application plan before exposing it. When internal services consume your API, you can set a default plan.
        ![An application plan is the API contract that establishes rules like access rights, limits, and pricing.](/packs/images/quick_starts/learn-about-application-plans.png "Learn about API contract.")
      # optional - the task's Check your work module
      review:
        instructions: |-
          - Did this task help you to learn about 3scale products?
        failedTaskHelp: This task isn’t verified yet. Try the task again.
      # optional - the task's success and failure messages
      summary:
        success: Shows a success message in the task header
        failed: Shows a failed message in the task header
  conclusion: |-
    **Next**
    To learn about API consumer’s account, API consumer’s device, and how to create application plan, see:
  # you can link to the next quick start(s) here
  nextQuickStart:
    - learning-about-accounts
    - learning-about-applications
    - creating-access-tiers-for-api-consumers
