name: Container
on:
  push:
    branches:
      - master
      - managed-services
      - 3scale-[0-9]+-stable
    tags:
      - 3scale-[0-9]+-GA
  workflow_dispatch:
    inputs:
      platforms:
        description: comma-separated list of platforms to build for, downstream supported are linux/amd64,linux/s390x,linux/ppc64le
        default: linux/amd64
      custom_tag:
        description: a custom tag on remote repo you want image to be tagged with
        default: scratch

jobs:
  call-build:
    uses: ./.github/workflows/container-image-buildah.yml
    with:
      platforms: ${{ inputs.platforms }}
      custom_tag: ${{ inputs.custom_tag }}
    secrets: # inherit doesn't work for some reason
      QUAY_USER_NAME: ${{ secrets.QUAY_USER_NAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
