name: Fast forward manually
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch name or commit to fast-forward from'
        required: true
        default: 'master'
      to_branch:
        description: 'The branch name to fast-forward to'
        required: true
        default: 'managed-services'

jobs:
  call-ff:
    uses: ./.github/workflows/fast-forward-branch.yml
    secrets: inherit
