name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 3 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: 'This PR is stale because it has not received activity for more than 30 days. Remove stale label or comment or this will be closed in 15 days.'
          days-before-stale: 30
          days-before-close: 15
